- server/api/plexapi.ts
- server/types/plex-api.d.ts
Corrects issue where the parameter 'port' for plex-api was incorrectly called 'post'.
- Fixes #276
> Changing parameter name to use correct 'port' #276

- Dockerfile
Allows for automated nginx reverse proxy setups to identify the port used in the container without having to bind the port to the host/localhost.
> Dockerfile: Expose port 3000.

- server/api/radarr.ts
Cleaned up the logging to not throw an error when the movie already exists in Radarr. Added more helpful logging so the user can understand what failed and why.
- References #260
> fix(services): improve logging for when Radarr movie already exists

- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
Aligned the poster, media text, and manage button on the movie and tv details page.
> fix(frontend): aligned movie and tv details

- src/components/Layout/Sidebar/index.tsx
Fixed being able to close the sidebars empty space when you click outside on mobile.
> fix(frontend): close sidebar when clicking outside

- .github/workflows/invalid_template.yml
Add workflow action that will comment and lock issues who's tag matches `invalid:template-incomplete`. The issue will be unlocked once the tag is removed.
None.
None.
> Add invalid template workflow

- server/api/sonarr.ts
- server/entity/MediaRequest.ts
Fixes the issue where the "Season Folders" toggle in Sonarr options does not actually pass the value on to Sonarr when adding series.
None.
None.
> fix(sonarr.ts, mediarequest.ts): add missing seasonFolder option

- .github/workflows/invalid_template.yml
Locking an issue will not allow the author to edit it. This will remove the lock from the workflow. 
- Fixes #XXXX
> docs: Remove the issue lock as it will not allow users to edit [skip ci]

- server/index.ts
Allow to listen server on specific host interface. Name is passed in HOST env variable similarly to PORT env variable.
- Fixes #273
> feat: allow to listen server on specific host interface

- Dockerfile
- README.md
- docker-compose.yml
- server/index.ts
- src/pages/_app.tsx
- src/pages/movie/[movieId]/index.tsx
- src/pages/tv/[tvId]/index.tsx
This will change the default internal port to 5055. This will help avoid future confusion about which port to use or forward to.
This PR, once merged, will break access to Overseerr for anyone who is accessing the app through the Docker portforward of 5055 to 3000. It will need to be updated to 5055 internally as well.
The README is updated as well with the new command.
> Change default internal port to 5055

- src/components/RequestBlock/index.tsx
Request slideover would break and force the element too wide on mobile. It will scale properly now.
> fix(frontend): changed request block for slideover on mobile UI

- public/site.webmanifest
This adds some missing parameters to the manifest for browsers to install it correctly.
N/A
None
> fix: add name, short_name and start_url to manifest

- src/components/RequestBlock/index.tsx
The approve and decline buttons will not fit in the container on mobile UI. Previously, they would be cut off on smaller mobile devices.
> fix(frontend): approve and decline button in manage slideover will now fit on mobile

- src/components/TvDetails/index.tsx
- src/i18n/locale/en.json
Now shows release date/first air date info on the TV details page similar to the movie details page.
- Fixes #463
> feat(frontend): first air date added to TV details page

- src/components/TitleCard/index.tsx
The restructuring done in f2ebba7 introduced an issue where the children of the animation would not be visible during the
animation
> fix(frontend): correctly position hover section

- src/assets/cross.svg
- src/assets/xcircle.svg
- src/components/Layout/SearchInput/index.tsx
- src/styles/globals.css
Clear input field icon was not visible on all devices, this replaces native ones with an svg button.
- Closes #423
> feat(frontend): add clear-field-icon to search field

- src/components/RequestModal/MovieRequestModal.tsx
This centers the auto approve message in the movie request modal for small devices only. 
It seemed weird on bigger screens, and along with the side panel not being hidden on these bigger screens, this decision makes sense to me.
On small devices:
On bigger devices:
N/A
- Fixes #507
> fix(frontend): center text in movie auto-approve modal on small screens only

- docs/support/faq.md
Add a reminder to check default user permissions before importing users from plex since mass editing of users is not possible at this moment.
N/A
N/A
N/A
> docs: added reminder to check default user permissions (#527) [skip ci]

- src/components/CollectionDetails/index.tsx
- src/components/Common/List/index.tsx
- src/components/Common/Modal/index.tsx
- src/components/Common/SlideOver/index.tsx
- src/components/Common/Table/index.tsx
- src/components/Layout/index.tsx
- src/components/Login/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/RequestBlock/index.tsx
- src/components/RequestList/index.tsx
- src/components/RequestModal/TvRequestModal.tsx
- src/components/Settings/Notifications/NotificationsDiscord.tsx
- src/components/Settings/Notifications/NotificationsEmail.tsx
- src/components/Settings/Notifications/NotificationsSlack/index.tsx
- src/components/Settings/Notifications/NotificationsTelegram.tsx
- src/components/Settings/RadarrModal/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/Settings/SonarrModal/index.tsx
- src/components/Setup/index.tsx
- src/components/Toast/index.tsx
- src/components/TvDetails/index.tsx
- src/components/UserEdit/index.tsx
- src/components/UserList/index.tsx
- tailwind.config.js
Status message would appear cutoff on smaller mobile devices such as an iPhone X. Full request modal for TV will not fit properly. Also removed a lot of unnecessary padding.
> fix(frontend): full season request modal fits on a smaller mobile UI

- docs/getting-started/installation.md
Moves install docs for native linux installs to their own chapter and divide them by tabs
> docs: Update Linux instructions #554 [skip ci]

- .github/workflows/snap.yaml
- docs/getting-started/installation.md
- snap/snapcraft.yaml
These changes provide a build process for snap packages. This will allow linux users to be able to install overseerr "natively". 
I created a workflow file that has been tested on my [fork](https://github.com/samwiseg0/overseerr/actions?query=workflow%3A%22Publish+Snap%22). It is currently triggered by a push to `develop` and any tags that start with `v`. At the end of the workflow is a discord notification for the workflow.  This can be removed if you prefer. 
Run this command to get the snapcraft secret. Currently the workflow only supports `edge` and `stable`. 
```
snapcraft export-login --snaps overseerr --channels edge,stable -
```
> Add snapcraft build yaml and workflow

- docs/extending-overseerr/reverse-proxy-examples.md
The example is currently bundled in SWAG, change wording to enable the subdomain the same way as the other samples
> docs(reverse-proxy): Add note for bundled sample SWAG (#681) [skip ci]

- overseerr-api.yml
- server/routes/request.ts
Adds `/request/count` endpoint which returns count of pending, approved, and available requests.
- Fixes #678
> feat(api): /request/count endpoint

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/snap.yaml
> build(release): Add snap package to the release workflow [skip ci]

- package.json
- yarn.lock
added resolutions such that node-sqlite3 depends on the latest version of node-gyp
Fixes build error related to sqlite3 on some platforms by using the latest version of node-gyp as a dependency resolution
- (Not Required)Translation Keys `yarn i18n:extract`
> fix(build): sqlite3 build error

- server/job/plexsync/index.ts
In case movie for Plex movie agent library does not have tmdbid - try looking it up by imdbid. 
No UI changed
afaik, no issue for this
> feat: lookup movie by imdbid if tmdbid does not exits for plex movie agent

- snap/snapcraft.yaml
This package seems to be a dependency to run overseerr on armhf platforms using snap. I am unable to test this past the syntax should be correct.
> build(armhf): Add libatomic1 to snap build for armhf

- package.json
- server/index.ts
- server/routes/auth.ts
- yarn.lock
add middleware to overwrite req.ip with the ip (can exist in a variety of places inside the request otherwise)
add the ip to the failed auth log on local user login
one of the tasks on #646
> feat(login): add request ip to the failed request log

- server/routes/user.ts
Local user creation was fixed to request permission. It should use default settings.
> fix(permissions): use default permissions when creating a local user

- README.md
- docs/extending-overseerr/reverse-proxy-examples.md
- docs/getting-started/installation.md
- server/index.ts
adds support for passing `PROXY` as an env var, which will be used to enable trusting proxy in express. This is required for the ip logging of failed authentication requests to work correctly.
- Closes #752
> fix(ip logging): add env var for proxy to fix ip logging

- docs/SUMMARY.md
- docs/extending-overseerr/fail2ban.md
This is a tutorial on how to setup fail2ban to protect Overseerr servers from brute-force attacks.
Users will be able to take advantage of the feature added via PR #714
> Setting up Fail2ban with Overseerr

- docs/extending-overseerr/fail2ban.md
- docs/getting-started/installation.md
- overseerr-api.yml
- server/index.ts
- server/lib/settings.ts
- src/components/Settings/SettingsMain.tsx
- src/i18n/locale/en.json
> **BREAKING CHANGE:** Users who have set `PROXY=yes` in their Docker containers will need to reconfigure this setting in the UI and restart Overseerr.
As discussed on Discord, this setting should be configurable via the UI.
> feat(ui)!: Move PROXY setting to UI

- .github/workflows/release.yml
Add `git checkout HEAD` to snap job to pull latest master.
> build(snap): Fix snap to pull from latest master [skip ci]

- README.md
`-e PROXY=<yes|no>` needs to be removed from `README.md` now that the setting has been moved to the UI.  (Also, it was missing a trailing `\` to escape the newline before. 😜)
Also added links to Sonarr, Radarr, and Plex and fixed some grammar errors/inconsistencies.
Do we want to mention the availability of Docker images on GitHub Container Registry (GHCR)?
N/A
> fix(readme): Remove PROXY env var and correct grammar/inconsistencies

- server/api/themoviedb.ts
- server/models/Tv.ts
- server/models/common.ts
This uses TMDb's `aggregate_credits` instead of `credits` to get the show's cast for all seasons.
Fixes #775
> feat(tv): show cast for the entire show instead of only the last season

- src/components/Layout/LanguagePicker/index.tsx
- src/context/LanguageContext.tsx
- src/pages/_app.tsx
Display language names in their respective languages in the language picker/dropdown, and order them alphabetically.
Also, correct the `zh-Hant` language code to `zh-TW`, which is what is expected by the TMDb API.
> fix(lang): Translate language names & change zh-Hant language code to zh-TW

- docs/extending-overseerr/reverse-proxy-examples.md
There is an issue with the CSP which results in Firefox blocking inline scripts.
I also noticed that Gravatar images were also broken due to a change made in PR #661 to fix issue #660.
Both of these issues are resolved with this PR.
> docs: Update LE/NGINX CSP to fix loading of resources

- src/components/Settings/RadarrModal/index.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/Settings/SonarrModal/index.tsx
- src/styles/globals.css
Size of the "port" text input fields in Plex, Sonarr, and Radarr settings should have class `w-24`.
> fix(ui): Restore original port input size

- src/components/Common/ButtonWithDropdown/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
Currently, when an item is available on Plex but there is no trailer available, an empty dropdown is shown.  This PR fixes that behavior.
Current:
Fixed:
- Fixes #787
> fix(ui): Don't display empty dropdown when no trailer available

- overseerr-api.yml
- server/interfaces/api/settingsInterfaces.ts
- server/lib/settings.ts
- server/routes/auth.ts
- src/components/Login/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsNotifications.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/UserList/index.tsx
- src/context/SettingsContext.tsx
- src/i18n/locale/en.json
- src/pages/_app.tsx
This PR adds an option to disable local user logins.  When disabled, the "Use your Overseerr account" option is hidden on the sign-in page, and the API will reject local login requests.  ~~A warning is also shown on the User List page when the option is disabled.~~
In the event that Plex OAuth is unavailable, this setting can be modified in `settings.json` to re-enable local user login functionality.
Settings page:
Login page:
- Fixes #647 and #766
> feat(ui): Add local login setting

- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
Currently, the "Mark 4k as Available" button is shown even if there is no 4k server.  This PR fixes this behavior, and only displays the button if 4k content is enabled.
> fix(ui): Hide 'Mark 4k as Available' button if 4k not enabled

- src/components/DownloadBlock/index.tsx
Currently, the download size is not verified to be nonzero, so it in some cases the download status is shown to the user as "NaN%."  This PR fixes this behavior.
- Fixes #829
> fix(frontend): Fix possible division by zero in download status

- Dockerfile
- overseerr-api.yml
- package.json
- server/routes/index.ts
- server/utils/appDataVolume.ts
- src/components/AppDataWarning/index.tsx
- src/components/Setup/index.tsx
- src/i18n/locale/en.json
A common issue for users who aren't familiar with Docker is that they find their Overseerr configuration/data wiped after an update/restart of the container.
This PR adds the creation of a zero-byte file to the Docker image in `/app/config`, which would only be visible to the container if the volume mount was not properly configured.
> feat(docker): Check for /app/config volume mount during setup

- src/components/Common/List/index.tsx
- src/styles/globals.css
Limits width of forms & lists, so that the gap between labels & their corresponding items does not become too big on large screens or when zoomed out.
- Fixes #844
> fix(ui): Limit max width of forms & lists

- overseerr-api.yml
- server/api/animelist.ts
- server/routes/index.ts
- server/utils/appDataVolume.ts
- src/components/AppDataWarning/index.tsx
- src/i18n/locale/en.json
Currently, the path to `/app/config` is hardcoded in the warning message if the volume mount was not configured properly for a Docker install.
This PR dynamically generates the path instead, so that if the path changes in the future or third-party images use a different path, the warning message is accurate/helpful to the user.
> fix(ui): Dynamically generate path to config in warning message

- src/components/Common/ListView/index.tsx
- src/components/MovieDetails/MovieCast/index.tsx
- src/components/MovieDetails/MovieCrew/index.tsx
- src/components/TvDetails/TvCast/index.tsx
- src/components/TvDetails/TvCrew/index.tsx
- src/styles/globals.css
Use consistent card sizes on non-mobile screens, so that they match those on the "Discover" home page.
This not only makes the card lists more pleasant to view at high resolutions, but also allows them to scale appropriately when zooming in/out.
**Before:**
**After:**
- Fixes #869
> fix(ui): Size cards appropriately based on base font size

- src/components/Login/index.tsx
Removes the rounded corners when use your overseer account is selected
Before:
After:
> fix(login): fix the gap when 'use your overseer account' was selected

- overseerr-api.yml
- server/routes/auth.ts
- server/routes/media.ts
- server/routes/request.ts
- server/routes/settings/index.ts
- src/components/Layout/UserDropdown/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/RequestBlock/index.tsx
- src/components/RequestButton/index.tsx
- src/components/RequestCard/index.tsx
- src/components/RequestList/RequestItem/index.tsx
- src/components/Settings/SettingsJobsCache/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/Setup/index.tsx
- src/components/TvDetails/index.tsx
`GET` should not be used for requests that mutate state; `GET` should be used solely for requests which only perform data retrieval.
From [RFC 7213](https://tools.ietf.org/html/rfc7231#section-4.2.1):
> **4.2.1.  Safe Methods**
> Request methods are considered "safe" if their defined semantics are essentially read-only; i.e., the client does not request, and does not expect, any state change on the origin server as a result of applying a safe method to a target resource.  ...  Of the request methods defined by this specification, the GET, HEAD, OPTIONS, and TRACE methods are defined to be safe.
As such, the CSRF token checking is disabled for `GET` requests, and we should take care to ensure that `GET` API endpoints only retrieve data, even if an action might be considered "low-risk." …
> fix(api): Use POST instead of GET for API endpoints that mutate state

- .github/workflows/ci.yml
Since we recently made changes to the `Dockerfile`, I decided to look through some of the GitHub Actions logs today and discovered that we actually aren't caching anything at all. 😅
This PR leverages [GitHub cache](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) using [`actions/cache`](https://github.com/actions/cache), as described here: https://github.com/docker/build-push-action#leverage-github-cache
> build(docker): Leverage GitHub cache using actions/cache

- .gitignore
- overseerr-api.yml
- server/api/themoviedb/index.ts
- server/api/themoviedb/interfaces.ts
- server/models/Movie.ts
- server/models/Tv.ts
- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
This adds content ratings for tv shows and movie ratings. The ratings default to either the US when available, or the first one in the response.
I added a border to the rating since it can be unclear as to what '15' is; for example: 
This also includes a small fix where the `|` between the runtime and genres on the movie detail page would be displayed even when there are no genres available.
On desktop:
On mobile:
None
- Fixes #685
> feat(ui): added content ratings for tv shows and movie ratings

- src/components/ResetPassword/RequestResetLink.tsx
- src/components/ResetPassword/index.tsx
- src/components/Settings/RadarrModal/index.tsx
- src/components/Settings/SonarrModal/index.tsx
- src/styles/globals.css
Some of the new form validation error messages are not using the `error` class.
Additionally, create and use a global class for the "required" indicator.
> refactor(css): Apply global CSS classes to form labels/validation

- server/entity/MediaRequest.ts
cleans up media and mediarequest when request to sonarr has failed because of tvdbid
- Fixes #873
> fix(requests): correctly clean up when tvdbid is missing

- docs/using-overseerr/notifications/webhooks.md
- server/entity/MediaRequest.ts
- server/lib/notifications/agents/agent.ts
- server/lib/notifications/agents/discord.ts
- server/lib/notifications/agents/pushover.ts
- server/lib/notifications/agents/slack.ts
- server/lib/notifications/agents/telegram.ts
- server/lib/notifications/agents/webhook.ts
- server/lib/settings.ts
- server/subscriber/MediaSubscriber.ts
- src/components/Settings/Notifications/NotificationsEmail.tsx
- src/components/Settings/Notifications/NotificationsTelegram.tsx
- src/components/Settings/Notifications/NotificationsWebhook/index.tsx
- src/i18n/locale/en.json
- Added handling of `MEDIA_FAILED` notifications to the Pushover, Slack, and Telegram agents.
- Refactored construction of notification messages/payloads to reduce the amount of duplicated code.
- Fixed formatting of notification messages for Pushover and Telegram agents for consistency.
- Added appropriate priorities to Pushover notifications.
- Send action URL using the `url` and `url_title` parameters instead of as part of the message body for Pushover notifications.
- Added option to send Telegram notifications silently.
- Added request ID to default webhook JSON payload (existing users will need to click the "Reset to Default" button or add it manually).
- Fixes #623
- Fixes #761
- Fixes #795
> feat(notif): Notification improvements

- package.json
- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
Small bugfix to correctly handle an empty array of movie/show attributes. 
Also includes a modification to the i18n script to use escaped double apostrophes instead of a single un-escaped ones.
N/A
- Fixes none
> fix(frontend): handle empty array of media attributes

- overseerr-api.yml
- server/constants/media.ts
- server/routes/request.ts
- src/components/RequestList/index.tsx
- src/components/RequestModal/TvRequestModal.tsx
- src/i18n/locale/en.json
Remove unused `MediaRequestStatus` enum value `AVAILABLE` , and add "Available" and "Processing" filter options to the request list page.
This is an alternative to #899 for implementing #656, using a more advanced query for the `/request` endpoint instead of trying to keep request statuses in sync with media statuses.
Currently still trying to find an elegant way to filter on and display availability for partial series requests (e.g., when a user only requests one season of a series and that becomes available, we should treat that as an available request even if other seasons are missing).
- Fixes #656
> feat(ui): Add 'Available' filter to request list and remove unused MediaRequestStatus.AVAILABLE enum value

- server/job/plexsync/index.ts
Existing code was expecting ratingKey to reference media item when adding movie.
But Hama stores movies as tv show episodes - so wrong ratingKey was used.
This change looks up first episode in first seasons for Plex media metadata (for 4K detection).
- Fixes #898
> fix(plex-sync): get correct Plex metadata for Hama movie items

- .github/workflows/invalid_template.yml
- .github/workflows/snap.yaml
1) This change disables `arm64` until we find a fix or workaround. Waiting on a response [here](https://forum.snapcraft.io/t/snapcraft-4-5-1-cannot-pack-data-prime-mksquashfs-call-failed-signal-segmentation-fault-core-dumped/22749).
2) Updated the snap workflow to include a job check. 
3) Changed invalid template workflow to close and lock and invalid issue. 
N/A
None
N/A
> build(snap): Disable arm64 snap build.

- server/entity/User.ts
- server/routes/auth.ts
No longer logs undefined when trying to login with emails that are connected to a user with no password.
- Fixes #771
> fix(auth): handle sign-in attempts from emails with no password

- server/templates/email/generatedpassword/subject.pug
- server/templates/email/media-request/subject.pug
- server/templates/email/resetpassword/subject.pug
- server/templates/email/test-email/subject.pug
Do not HTML-escape email subjects, to prevent unwanted character sequences like `&amp;`.
More info: https://pugjs.org/language/code.html#unescaped-buffered-code
N/A
- Fixes #927
> fix(notif): Do not HTML-escape email subjects

- src/components/PermissionEdit/index.tsx
- src/components/PermissionOption/index.tsx
Some permissions are dependent on other, non-parent permissions.  For example, "Auto-Approve 4K" is dependent on both "Request" (general request permission) and "Request 4K" (4K content request permission).  This PR adds a check for requirements for a particular permission, and disables and unchecks a permission if that condition is not satisfied.
> fix(ui): Automatically disable and uncheck user permissions with unmet requirements

- server/routes/user/usersettings.ts
- src/components/PermissionEdit/index.tsx
- src/components/PermissionOption/index.tsx
- src/components/UserList/BulkEditModal.tsx
- src/components/UserProfile/UserSettings/UserPermissions/index.tsx
Since the first user is tied to the Plex media server instance, we currently do not allow deletion of this user.  This PR adds protection against attempts to remove the "Admin" permission from this user.
> fix(frontend): Do not allow user w/ ID 1 to disable 'Admin' permission

- src/components/RequestModal/AdvancedRequester/index.tsx
`AdvancedRequester` was not updated in #957, which results in a runtime error.
> fix(frontend): Update AdvancedRequester to reflect new /user API response

- server/lib/notifications/agents/telegram.ts
Removes extra newlines from "Now Available" Telegram notifications.
> fix(notif): Remove extra newlines from Telegram notifications

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/stale.yml
@sct This PR is just my suggestions/opinions for improvement, and I understand if you don't want to change certain things.
It really bothers me that the PR template uses headings, whereas the issue templates use bolded text.  Changing this would enable us to use an action such as [lucasbento/auto-close-issues](https://github.com/lucasbento/auto-close-issues) to automatically label and close issues that do not follow the template.  It also has the advantage of automatically re-opening issues if a user fixes the template! 😉  I think that this would help greatly with issue management, especially as Overseerr grows and becomes more popular.
I also corrected the spelling error in the PR template and edited heading names, etc. for consistency/clarity.
N/A
N/A
N/A
> chore(github): Edit templates for consistency

- src/components/TvDetails/index.tsx
Incorrect download status array is being used for the 4K status badge on TV series detail pages.
N/A
> fix(ui): Display 4K download status on 4K status badge

- src/components/Settings/SettingsLayout.tsx
- src/components/Settings/SettingsNotifications.tsx
Fix navigation display issue in Settings in cases where the window/viewport is not wide enough to display all options/tabs without scrolling.
- Before:
- After:
N/A
> fix(ui): Fix settings navigation horizontal scroll issues

- .github/workflows/release.yml
- .github/workflows/snap.yaml
The issue with the snap packages and `arm64` appear to be related to the latest QEMU version. This change reverts QEMU to a known working version. We will have to park QEMU for snap build until there is a fix. 
N/A
N/A
N/A
> build(snap): Revert QEMU version to fix arm64 builds

- server/interfaces/api/settingsInterfaces.ts
- server/lib/settings.ts
- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
- src/context/SettingsContext.tsx
- src/hooks/useUser.ts
- src/pages/_app.tsx
Movie/TV ratings are associated with releases, and we currently return the rating associated with a US release if one exists.
This changes the behavior to use the global or user region setting, and to fall back to the US region only if those are both set to "All Regions."
N/A
N/A
> fix(frontend): use region settings instead of hardcoded 'US' value for movie/TV ratings

- server/lib/notifications/agents/telegram.ts
- src/components/Settings/Notifications/NotificationsTelegram.tsx
- src/i18n/locale/en.json
When the custom application title contained certain special characters, Telegram notifications would fail to send.
Also, removed the validation on the chat ID field since it does not account for some chat IDs which begin with a special character.
N/A
- Fixes #1010
> fix(notif): escape application title in Telegram notifications

- .github/workflows/support.yml
When issues are tagged as support, lock conversation in addition to closing them.
N/A
N/A
N/A
> chore(github): lock closed support issues

- src/components/Settings/SonarrModal/index.tsx
The toast showed a shows string instead of the internationalized one. This fixes that.
- Fixes none
> fix(ui): show translated string on sonarr sucesss/failure toast messages

- src/components/UserProfile/UserSettings/UserPasswordChange/index.tsx
- src/components/UserProfile/UserSettings/index.tsx
- src/i18n/locale/en.json
No reason to allow the user to visit this tab/page if they can't change the password. :)
N/A
> fix(ui): don't show "Password" user settings tab if current user lacks perms to modify the password

- Dockerfile
- Dockerfile.local
Node v14.x (LTS) update from 2021-02-23 (includes vulnerability fixes)
https://nodejs.org/en/blog/release/v14.16.0/
N/A
N/A
> build(docker): bump node from 14.15 to 14.16

- src/components/Settings/SettingsServices.tsx
I personally would appreciate an easier way to navigate directly to the Radarr/Sonarr instance from the settings page. 😉  Also display the full address, including scheme (http/https) and port, and removed usage of `FormattedMessage`.
N/A
> feat(ui): in Settings > Services, make Radarr/Sonarr server names and logos clickable links

- src/components/TvDetails/index.tsx
- src/i18n/locale/en.json
Add season count to TV details pages in the location where movie runtime would be displayed on movie details pages.
N/A
> feat(ui): display season count on TV details page

- src/components/Discover/DiscoverNetwork/index.tsx
- src/components/Discover/DiscoverStudio/index.tsx
There is no `alt` text for the studio/network logos on the filtered Discover pages, so this PR adds that.
Also noticed that a blinking text cursor would appear either before/after the logos, so fixed that as well.
**Blinking text cursor:**
N/A
> fix(ui): add alt prop to studio/network logos & fix blinking text cursor

- src/components/Setup/LoginWithPlex.tsx
Apply the fix from c4af4c42ab00f1a63a2f5326c9cd8b26c19f4f14 to the setup flow as well.
N/A
> fix(frontend): check for ID instead of email after initial setup Plex login

- src/components/RequestCard/index.tsx
- src/components/RequestList/RequestItem/index.tsx
- src/styles/globals.css
- tailwind.config.js
Removal of the `overflow-hidden` class in a couple places when the poster link was added broke the request item display when the season list is too long.
Fixed that and also made user avatars behave in a similar way to the posters on link hover.
Before:
After:
N/A
> fix(ui): fix request list UI behavior when season list is too long

- docs/extending-overseerr/reverse-proxy-examples.md
Add a workaround `nginx` subfolder reverse proxy configuration to the documentation.
This method is super hacky and is prone to break if Overseerr updates any of the paths rendering the `sub_filter`s invalid.
- Workaround for #274
> docs(proxy): add nginx subfolder reverse proxy (#1114) [skip ci]

- .github/workflows/ci.yml
Nothing is getting cached during the first build stage, so we should stop writing it to the cache.
Also, "[at] the moment caches are copied over the existing cache so it keeps growing. The Move cache step is used as a temporary fix..." (https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache).
N/A
N/A
N/A
> ci(docker): don't cache first build stage, and add temp fix for growing cache

- server/routes/discover.ts
Networks/studios tend to produce content only in certain languages/regions, so it does not make sense to filter these results.  (Currently, if there is global/user language/region filtering, results for some studios/networks will be empty.)
N/A
> fix: remove language/region filtering on studio/network results

- src/components/MovieDetails/index.tsx
Currently links to TV results instead of movie results, whoops!
N/A
> fix: fix language filter link on movie detail pages

- src/components/RequestList/RequestItem/index.tsx
Fixes inconsistent button sizing.  Note that some languages with really long "Approve" / "Decline" strings (only Hungarian, currently) will still see some inconsistencies between rows of the request list.
N/A
> fix(ui): request list button sizes

- src/components/Settings/Notifications/NotificationsPushover/index.tsx
- src/components/Settings/Notifications/NotificationsTelegram.tsx
- src/i18n/locale/en.json
Our input validation on Pushover tokens/keys is too strict, so relax the check to only verify that 30-character alphanumeric strings are inputted.
Also fix a string on the Telegram notifications page.
- Fixes #1165
> fix(notif): loosen input validation on Pushover settings

- server/lib/notifications/agents/discord.ts
- **Before:**
- **After:**
N/A
> fix(notif): set URL for Discord embeds rather than adding a field for the link

- src/components/RequestModal/AdvancedRequester/index.tsx
Request overrides should not allow user to select 4K servers for non-4K requests, or non-4K servers for 4K requests.
N/A
> fix(ui): filter out server options that do not match request type (non-4K or 4K)

- src/components/RegionSelector/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
Currently, items in the dropdowns are not actually alphabetized by the strings displayed to the user, but by the English names returned from TMDb.
Not only does this result in the list not being alphabetized in non-English languages, but it actually causes some entries to appear out of order in English as well.
One example is the "zh" language code, for which TMDb returns an English name of "Mandarin" but is usually localized to "Chinese."
N/A
> fix(ui): sort regions & languages by their localized names rather than their TMDb English names

- src/components/Settings/Notifications/NotificationsEmail.tsx
- src/components/Settings/RadarrModal/index.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/Settings/SonarrModal/index.tsx
Adds validation to hostname fields in Sonarr & Radarr modals, Plex settings, and email notification settings.
Also fixes Sonarr & Radarr modals so it doesn't allow testing when there are errors in the inputs.
N/A
> fix(ui): hostname field validation

- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsPlex.tsx
Makes it clearer that `readonly` input fields cannot be interacted with, since otherwise they appear like regular text boxes.  (Currently, there are only two such fields... the API key in General Settings, and the server name in Plex Settings.)
N/A
> fix(ui): use appropriate cursor type for readonly input fields

- src/i18n/locale/en.json
- src/pages/404.tsx
I missed the fact that the error message w/ code string was being shared in two files (#1202).  Currently, the status code will always appear as 404. 😅 
N/A
> fix(lang): fix overwritten/shared string

- src/components/Settings/SettingsLogs/index.tsx
- src/components/UserList/index.tsx
Adds a page query parameter to the logs page, similar to that added to the request list in 7aa0239cd99d41048da90203331bf3080aa0ae5e.
Also fixes the timestamp so that "24" is not displayed to the user as the hour in some instances.
N/A
> refactor(ui): add page query param to logs page & user list, and fix log timestamps

- server/entity/MediaRequest.ts
- server/lib/notifications/agents/agent.ts
- server/lib/notifications/agents/discord.ts
- server/lib/notifications/agents/email.ts
- server/lib/notifications/agents/pushbullet.ts
- server/lib/notifications/agents/pushover.ts
- server/lib/notifications/agents/slack.ts
- server/lib/notifications/agents/telegram.ts
- server/lib/notifications/index.ts
- server/templates/email/media-request/html.pug
- Adds requested season numbers to all notification types (only Discord notifications included this information previously)
- Sets `notifyUser` only for user-specific notification types (`MEDIA_APPROVED`, `MEDIA_DECLINED`, `MEDIA_AVAILABLE`), since otherwise notifications will go to all admins
- Fixes email agent using the PGP key of the media requester rather than that of the email recipient for admin notifications
- Includes media plot/overview in `MEDIA_FAILED` notifications, since we are already showing a failure message in the subject of those notifications
- Closes #315
> feat(notif): include requested season numbers in notifications

- server/routes/settings/index.ts
This allows labels made up of at least one character to be matched when parsing the logs.
None
None
- Fixes none
> fix(ui): better regex matching when parsing logs

- src/components/Settings/SettingsLogs/index.tsx
- src/i18n/locale/en.json
"Extra Data" implies that the data is unnecessary/superfluous, but this data is really just additional details about the specific log event.
N/A
> fix(lang): change 'Extra Data' string to 'Additional Data'

- server/routes/settings/index.ts
Properly parse labels for log messages that have json in them
None
- Fixes none
> fix(ui): fix regex matching when parsing label from logs

- src/components/Setup/index.tsx
- src/pages/_app.tsx
Redirect users from `/setup` if Overseerr is also initialized.  Also fix positioning of logo on setup pages so that it is centered.
N/A
> fix(frontend): redirect from /setup if already initialized

- src/components/DownloadBlock/index.tsx
- src/components/RequestList/RequestItem/index.tsx
- src/components/Settings/SettingsAbout/Releases/index.tsx
- src/components/Settings/SettingsJobsCache/index.tsx
Sets `numeric` attribute of `FormattedRelativeTime` elements to `auto`. This fixes cases where a string like "in 0 seconds" will be displayed to the user, instead of a more readable string like "now."
N/A
> fix(ui): do not require numeric value in FormattedRelativeTime

- src/components/Settings/SettingsLogs/index.tsx
This PR makes it so that the 'Show Details' button on the logs page is only displayed if there are additional details (for e.g. in Plex Scan error log messages).
None
- Fixes none
> fix(ui): hide 'show details' button if there are no additional details

- docs/SUMMARY.md
- docs/using-overseerr/notifications/README.md
- docs/using-overseerr/notifications/discord.md
- docs/using-overseerr/notifications/email.md
- docs/using-overseerr/notifications/webhooks.md
Adds email & Discord info to documentation. (Documentation for other notification agents is not included in this PR.)
N/A
N/A
> docs: add email & Discord notification info

- src/components/Settings/SettingsLogs/index.tsx
- src/components/UserList/index.tsx
Use localStorage to remember the sort order and page size of the user list just like it's done for the requests list and logs.
N/A
- Fixes none
> feat(ui): store sort order and page size of userlist in localstorage

- public/site.webmanifest
Define icons in `site.webmanifest` with a `purpose` of `maskable`, so that icons are displayed properly on Android devices.
**Before & After:**
N/A
N/A
> feat(android): adaptive icons for Android devices

- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
Currently, the "Enable Override" checkboxes reset to unchecked when you return to the user settings page after  saving.  (This is just a visual bug, the values are saved properly to the DB.)
N/A
> fix(ui): restore saved states of quota override checkboxes

- overseerr-api.yml
Quick fix for the API definitions where Pushbullet was referencing the wrong schema and had an incorrect summary & description.
Similar fix for webhook, which referenced the wrong schema.
- No open issues regarding this fix.
> fix(overseerr-api.yml): Fixed Pushbullet & webhook API definition refs and descriptions

- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsServices.tsx
Call mutate to `/api/v1/settings/public` after changing public settings to force refresh/update of settings.
N/A
> fix(frontend): call mutate after changing public settings

- src/components/RequestModal/QuotaDisplay/index.tsx
When submitting a request on behalf of another user, the user profile page link is currently broken (links to `/user/[userId]` instead of `/users/[userId]`).
N/A
> fix(frontend): use correct path to user profile in request modal quota dropdown

- src/components/Discover/index.tsx
- src/components/RequestList/index.tsx
The "Recent Requests" slider on the Discover page only shows "unavailable" requests -- requests with any request status, but with media status of any value but "available."
This slider should link to a request list view with the same filter, so this PR adds the missing filter type to the request list and updates the slider link to pass a new `filter` query parameter.
**Edit:** Changed "Recent Requests" slider and its link to use the "all" instead of "unavailable" filter.
N/A
> fix(frontend): 'Recent Requests' slider should link to request list w/ same filter

- overseerr-api.yml
- server/routes/request.ts
- src/components/RequestList/index.tsx
- src/components/UserList/index.tsx
- src/components/UserProfile/index.tsx
- src/hooks/useRouteGuard.ts
- src/hooks/useUser.ts
- src/pages/users/[userId]/requests.tsx
Adds a request list view at `/users/[userId]/requests` that only displays one user's requests.  The "Recent Requests" slider heading links to this page.
> feat(ui): Add user requests page

- src/components/Layout/LanguagePicker/index.tsx
- src/context/LanguageContext.tsx
- src/pages/_app.tsx
Adds Catalan to the language picker. Should be merged after #1305.
N/A
> feat(lang): add Catalan to language picker

- src/components/Settings/SettingsLogs/index.tsx
When the buttons for each log line were added, the colspan wasn't updated.
PR fixes this issue:
N/A
> fix(ui): use correct colspan for 'No results.' message in Settings > Logs

- docs/using-overseerr/settings/README.md
~~Clarify that the image cache location is inside the container/VM.~~
Remove mention of the image cache direcctory path, as we do not want users to add volume mounts at this time.
N/A
N/A
> docs: remove image cache directory path

- src/components/QuotaSelector/index.tsx
Allows for users to select any value from 1 to 100 for the quota limit & days.
Users would be able to set a request limit as low as 1 request per 100 days, or as high as 100 requests per 1 day.
IMO, this is a good compromise between only allowing a few options and switching to a text box (where the "Unlimited" option then becomes less clear/intuitive).
- Closes #1285
> feat(ui): allow any value 1-100 for quota limit/days

- src/components/TitleCard/index.tsx
Title card fixes:
- Truncate titles if they span more than 3 lines
- Break long words if necessary to prevent overflow
N/A
> fix(ui): gracefully handle lengthy titles & long words in overviews

- server/api/themoviedb/index.ts
Currently, we are logging messages such as the following:
```
2021-03-29T08:30:25.985Z [error][Sonarr Scan]: Failed to process Sonarr media {"errorMessage":"[TMDb] Failed to get TV show using the external TVDB ID: [TMDb] Failed to find a TV show with the provided TVDB ID: 309496","title":"Rock Records In Love"}
```
This is because we are throwing an error in `getShowByTvdbId()` which gets caught by a `try`/`catch` block which then re-throws and adds to the message.
N/A
> fix(backend): fix getShowByTvdbId() error message

- src/components/Discover/NetworkSlider/index.tsx
- src/components/Discover/StudioSlider/index.tsx
> fix(frontend): use HTTPS to fetch TMDb assets for network/studio sliders

- src/components/ExternalLinkBlock/index.tsx
Include the `language` query parameter in TMDb external links, so that the user is directed to the appropriately localized page.
N/A
> fix(frontend): include language parameter in TMDb links

- src/components/RequestCard/index.tsx
Plex URLs aren't being passed to the `StatusBadge` component for `RequestCard`s currently.
N/A
> fix(ui): link request card status badge to Plex media URL

- server/api/themoviedb/index.ts
TMDb returns `null` for genre names in some languages (e.g., Catalan), which results in odd behavior for those locales (genre cards with no text and genre pages with no genre name).
This PR adds a fall back to English genre names when a localized name is not provided by TMDb.
**Note:** TMDb _is_ falling back to English genre names in the `genres` object returned by their `/movie/{movie_id}` and `/tv/{tv_id}` API endpoints (used by movie/series detail pages).  They simply aren't falling back to English on their `/genre/movie/list` and `/genre/tv/list` endpoints. 🤦🏻‍♀️
- Fixes #1349
> fix: fall back to English genre names

- overseerr-api.yml
- server/routes/settings/index.ts
This PR updates the `/plex/devices/servers` API endpoint to try to connect to Plex using the returned `address` property, rather than trying to parse the hostname out of the `uri` property.
This resolves an issue with automatic server configuration reported by the folks over at LSIO 🐱
N/A
> fix(plex): use server 'address' returned by Plex API

- .gitattributes
- server/entity/User.ts
re #1358
This would cause inaccurate quota rules applied to new requests, as it may or may not artificially
extend the actual cooldown period.
Also added .gitattributes for the pesky windows users that have different line endings than the repo
- Request limit hit at 3PM.
- Day one of the cooldown is the next day (3PM -> 3PM then cut off time time value so we're just at the next day)
- Day two of the cooldown period is the next after that (3PM -> 3PM again then cut of the time again)
- Day 3 at 12:01AM they are able to request again.
This means that 48 hours + 9 hours (3PM -> 11:59PM on the first day) have passed since requesting = 57 hours.
- Fixes #1358
> fix(user.ts): Time value of a quota was being ignored

- docs/SUMMARY.md
- docs/using-overseerr/notifications/README.md
- docs/using-overseerr/notifications/discord.md
- docs/using-overseerr/notifications/email.md
- docs/using-overseerr/notifications/pushbullet.md
- docs/using-overseerr/notifications/pushover.md
- docs/using-overseerr/notifications/slack.md
- docs/using-overseerr/notifications/telegram.md
- docs/using-overseerr/notifications/webhooks.md
This PR adds documentation for the Pushbullet, Pushover, Slack, and Telegram agents.
It also reflects the changes/fixes implemented in #1172, so it should not be merged until after that PR is in `develop`.
Many thanks to @costaht for helping with the Telegram docs!
N/A
N/A
> docs: add Pushbullet, Pushover, Slack, Telegram

- server/interfaces/api/plexInterfaces.ts
- server/routes/settings/index.ts
- src/components/Settings/SettingsPlex.tsx
Plex returns `https` as the protocol even for local IPs, which causes a `Hostname/IP does not match certificate's altnames` error when we test the connection using that particular config.
N/A
> fix(plex): do not use SSL for local servers

- server/api/plextv.ts
Fixes `Error checking user access: Cannot read properly ‘find’ of undefined` error when importing users and a user does not have access to any servers.
N/A
> fix(plex): do not log error when attempting to import user w/ no server access

- .github/workflows/ci.yml
- .github/workflows/release.yml
https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio
> GitHub Container Registry now supports `GITHUB_TOKEN` for easy and secure authentication in your workflows. If your workflow is using a personal access token (PAT) to authenticate to `ghcr.io`, then we highly recommend you update your workflow to use `GITHUB_TOKEN`.
> ...
> Using the `GITHUB_TOKEN` instead of a PAT, which includes the `repo` scope, increases the security of your repository as you don't need to use a long-lived PAT that offers unnecessary access to the repository where your workflow is run. ...
**Note:** Actions access needs to be configured for the GHCR package before merging this PR.  (See step 3 in the above link.)
N/A
N/A
> ci(github): authenticate with GHCR using GITHUB_TOKEN instead of PAT

- src/components/UserList/index.tsx
Dims password field in `Create Local User` modal when `Automatically Generate Password` is checked, so that it is clearer that the password field is disabled.
N/A
> fix(ui): dim password field when password generation option is selected

- src/components/Login/LocalLogin.tsx
- src/components/ResetPassword/index.tsx
- src/components/UserList/index.tsx
- src/components/UserProfile/UserSettings/UserPasswordChange/index.tsx
- src/i18n/locale/en.json
Sets `autocomplete` attribute for passwords to `new-password` or `current-password` as appropriate.  (This also fixes the undesired behavior of the `Create Local User` modal trying to autofill with saved emails/passwords.)
Also adds a tip for the `Automatically Generate Password` option to clarify that the generated password will be emailed to the user.
N/A
> fix(ui): correctly set autocomplete attribute for password fields

- src/components/UserList/index.tsx
Adjusts user list buttons so that they are on separate lines and do not wrap on mobile.
N/A
> fix(ui): adjust user list buttons on mobile

- src/components/Common/PlayButton/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
Currently, only the main/default action in the `PlayButton` component has an icon. This PR adds icons for all items in the dropdown menu, to be consistent with the `RequestButton` component, for which every action/option has an icon.
N/A
> refactor(ui): add icons to PlayButton dropdown

- server/routes/user/usersettings.ts
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
Currently, when an admin modifies the `Display Language` setting for another user, the current locale is incorrectly changed for the current/acting user as well.
N/A
> fix: do not set locale when modifying other users

- server/lib/email/index.ts
Parses the hostname from the `Application URL` setting and explicitly sets that value as the Nodemailer SMTP transport `name` option.
Default Nodemailer behavior is unchanged when `Application URL` is not set.
More info: https://nodemailer.com/smtp/#connection-options
N/A
- Fixes #1515
> fix(email): specify Nodemailer SMTP transport 'name' option

- server/lib/scanners/radarr/index.ts
Changes behavior of Radarr scanner to not mark unmonitored movies as `Requested`.
N/A
- Fixes https://github.com/sct/overseerr/issues/1286#issuecomment-827582789
> fix(radarr): only process Radarr movies which are either monitored or downloaded

- src/components/MovieDetails/index.tsx
- src/components/RequestBlock/index.tsx
- src/components/Settings/SettingsLogs/index.tsx
- src/components/TvDetails/index.tsx
- src/styles/globals.css
Removes button icon styling using the `last:` variant in favor of new `icon-md` and `icon-sm` classes, as not all buttons conformed to same pattern.
N/A
> fix(css): fix cog icon size on media detail pages

- src/components/Settings/SettingsPlex.tsx
Button text needs to be wrapped in a `span` element in order for the SVG icon to not be the "last" element.
- Before:
- After:
N/A
> fix(ui): add missing margins on button SVGs on Plex Settings page

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/snap.yaml
`actions/cache@v2.1.5` does not support BusyBox `tar`, so we need to use `v2.1.0` for this action to work in the Alpine container environment.
More info: https://github.com/actions/cache/issues/425#issuecomment-703114994
N/A
N/A
N/A
> ci: use actions/cache@v2.1.0 instead of v2.1.5 for Next.js build cache

- server/lib/settings.ts
- src/components/LanguageSelector/index.tsx
- src/components/RegionSelector/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
When multiple languages are selected for the `Discover Language` server setting, the fallback logic does not use the individual language code to determine the TMDb English name, but the entire `|`-delimited string (e.g., `en|zh|ko`).
In addition to fixing that bug, this PR also refactors sorting and name fallback logic for both the `LanguageSelector` and `RegionSelector`, to use `lodash` `sortBy` and remove duplicated code for `intl.formatDisplayName` & TMDb `english_name` fallbacks.
- Before:
- After:
N/A
> fix: correctly fall back to English name in LanguageSelector

- .github/workflows/ci.yml
- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/snap.yaml
- Dockerfile
Refactors the `Dockerfile` to enable caching of `node_modules`, by copying `package.json` & `yarn.lock` first and doing the initial `yarn install` before copying in the remainder of the source files and building.
During local testing with `buildx`, this resulted in a 45% reduction in total build time 👀  (See screenshots below!)
Also:
- Removed Next.js caching as it requires GNU `tar` and it isn't worth it to install additional packages
- Removed `actions/cache` from preview build workflow.
- **Initial build:**
- **Second build (with different `COMMIT_TAG` and no changes to `package.json` or `yarn.lock`):**
N/A
N/A
> build(docker): refactor Dockerfile to enable caching of node_modules

- src/components/DownloadBlock/index.tsx
- src/components/RequestBlock/index.tsx
- src/i18n/locale/en.json
- Makes names of users in the `RequestBlock` clickable links
- Changes `ETA` string in `DownloadBlock` to `Estimated` (and creates a translation string; one did not exist previously)
- Simply do not display estimated time if none available (instead of `N/A`)
- Use spacing for badges consistent with other places in UI
N/A
> fix(ui): add user profile links to RequestBlock and change 'ETA' string in DownloadBlock

- src/components/RegionSelector/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
- src/styles/globals.css
`rounded-l-only` is only being applied to `input` and `select` elements, but needs to be applied to `textarea`s as well.
Also increases the maximum width of input elements and slightly reduces the horizontal padding on the input action buttons, since they can make the actual input box pretty narrow when there are several actions.
**Before (desktop):**
**After(desktop):**
**Before (mobile):**
**After (mobile):**
N/A
> fix(ui): apply rounded-l-only to SensitiveInput textareas and increase visible text input area

- server/routes/index.ts
- src/components/Settings/Notifications/NotificationsWebPush/index.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsWebPush.tsx
Users who opt out of receiving web push notifications should not be prompted to allow notifications in their browser.
N/A
> fix(webpush): only prompt user to allow notifications if enabled in user settings

- package.json
- server/lib/email/openpgpEncrypt.ts
- yarn.lock
Resolves build failure in Dependabot PR #1517 from breaking changes in `openpgp` 🐱
N/A
N/A
> build(deps): bump openpgp from 5.0.0-1 to 5.0.0-2

- src/components/Common/SensitiveInput/index.tsx
Fixes input type being undefined (see screenshots below).  I accidentally introduced this bug in #1563 🙈
**Before:**
**After:**
N/A
> fix(ui): default to text input type for SensitiveInputs

- src/components/Layout/index.tsx
- src/components/Setup/index.tsx
The sign-in page uses the server default locale.  However, the locale should be set to the user's preference once they log in.
Currently, a page refresh is required for the user-set locale to take effect after signing in.
N/A
N/A
> fix(locale): set locale based on user settings upon login

- src/components/Settings/SettingsPlex.tsx
Upon saving Plex server settings, automatically sync the library list so that users are not required to click the button.
Also, fix an issue that only occurs during the setup flow, where an error will incorrectly display under the `Hostname` field after the initial selection of a server preset.
N/A
N/A
> fix(plex): sync libraries after saving settings

- src/components/RequestModal/AdvancedRequester/index.tsx
- src/i18n/locale/en.json
The advanced request options are cool, but they also unnecessarily take up valuable screen estate for those who don't have multiple servers, profiles, tags, etc. to choose from.
This PR hides any advanced request options for which there is only one choice (or, in the case of tags, when there are no tags).
N/A
> fix(ui): hide advanced request options when there is only one choice

- server/routes/settings/notifications.ts
- src/components/Settings/Notifications/NotificationsWebPush/index.tsx
- src/components/Settings/SettingsNotifications.tsx
- src/i18n/locale/en.json
Web push notifications only work when Overseerr is being served over HTTPS, so we should warn users about the requirement.
This PR adds a warning to the web push settings page that only appears when accessed over HTTP.
**Accessed via HTTP:**
**Accessed via HTTPS:**
N/A
> feat(webpush): add warning to web push settings re: HTTPS requirement

- src/components/Settings/SettingsPlex.tsx
- src/components/UserList/index.tsx
- src/i18n/locale/en.json
The Plex info alert box isn't really necessary after the initial setup.
And since we've now moved the `Enable Local Sign-In` setting to the `Settings > Users` (it used to be in `Settings > General`), I think it's worth having an alert in the `Create Local User` modal.
N/A
> fix(ui): hide Plex alert after setup & add warning to create user modal when local sign-in is disabled

- server/routes/request.ts
When checking for an existing movie request, we shouldn't filter out requests made by other users, since there can be only one "regular" request and one 4K request for any given movie.
N/A
N/A
> fix: remove requestedBy user param from existing movie request check

- src/components/StatusBadge/index.tsx
"Pointer" cursor style should be applied for status badges that link to Plex, instead of the default cursor style.
N/A
> fix(ui): apply pointer cursor style for clickable status badges

- src/components/RequestCard/index.tsx
Removes delete button from request cards to reduce likelihood of accidental deletion of requests.
N/A
> fix(ui): remove delete button from request cards

- overseerr-api.yml
- server/api/themoviedb/index.ts
- src/components/Layout/LanguagePicker/index.tsx
- src/components/Layout/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
- src/context/LanguageContext.tsx
- src/pages/_app.tsx
Adds support for Greek ~~and Polish~~ display language~~s~~ (should be merged after #1603).
Also:
- Renames `zh-TW` display language to 繁體中文‬
- Fixes plurality of `AvailableLocale` type name (previously `AvailableLocales`)
- Consistently uses `en` as fallback/default language (instead of `en-US`)
N/A
N/A
> feat(lang): add Greek display language

- src/components/RequestModal/TvRequestModal.tsx
Currently, when editing an existing TV series request, seasons in the existing request are being counted twice.
N/A
- Fixes #1648
> fix(quotas): do not count already-requested seasons when editing TV request

- src/components/Common/SensitiveInput/index.tsx
The hide/unhide button for the `SensitiveInput` component needs to explicitly specify `type="button"` to prevent it from capturing enter key inputs.
N/A
- Fixes #1647
> fix(sensitiveinput): do not capture enter key input

- server/middleware/auth.ts
- src/components/Layout/index.tsx
- src/pages/_app.tsx
Currently, the user's locale setting is being lost upon page refresh.
N/A
- Fixes #1645
> fix(locale): properly restore display language upon page refresh

- src/components/Common/SettingsTabs/index.tsx
Apply missing `overflow-x-scroll` Tailwind CSS class to "main" settings tabs.
I suspect this is the root cause of #1582, so that issue may be resolved by this PR.
- Maybe #1582
> fix(ui): correct horizontal overflow behavior of settings tabs

- src/pages/_error.tsx
The language string is `'{statusCode} - {error}'`, but `message` is being specified instead of `error`.
N/A
N/A
> fix: correctly display error messages

- server/lib/scanners/baseScanner.ts
When there is no season data on TVDB, Sonarr will return 0 seasons and the scanner will set the media status to `UNKNOWN` (since there are no seasons with status `PROCESSING`).
This PR adds a check to see if no seasons were passed to `processShow()`.  This should only impact Sonarr scans, since in order for series to exist / be picked up by a Plex scan, they must have at least one episode (and thus at least one season result).
N/A
- Fixes #1690
> fix(sonarr): do not mark media as failed if there is no season data on TVDB

- server/lib/notifications/agents/discord.ts
- server/lib/notifications/agents/email.ts
- server/lib/notifications/agents/webpush.ts
Email and webpush agents will filter out these users. Discord agent won't @ them.
- Fixes #1707
> feat(notif): prevent manage-request users receiving auto-approve notif from their requests

- server/entity/User.ts
- server/routes/auth.ts
- server/routes/user/index.ts
- src/components/RequestModal/AdvancedRequester/index.tsx
- src/components/UserList/index.tsx
- src/components/UserProfile/ProfileHeader/index.tsx
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
Managed users do not have email addresses, which causes the DB query to check for an existing user to fail when we attempt to lowercase the e-mail address.
Also:
- ~~Do not set username when it is the same as the user's email address~~
- Fix weird UX when a user doesn't have a username set
- Make the display name sort on the user list case-insensitive
- Set appropriate placeholder for display name field (so it reflects what the user's display name would be if they do not set a username)
- Hide user email addresses from users without the `Manage Users` permission (unless the user does not have a display name set, in which case their email address is also their display name)
N/A
- Fixes #1698
> fix(plex): do not fail to import Plex users when Plex Home has managed users

- src/pages/settings/logs.tsx
- src/pages/settings/notifications/discord.tsx
- src/pages/settings/notifications/email.tsx
- src/pages/settings/notifications/lunasea.tsx
- src/pages/settings/notifications/pushbullet.tsx
- src/pages/settings/notifications/pushover.tsx
- src/pages/settings/notifications/slack.tsx
- src/pages/settings/notifications/telegram.tsx
- src/pages/settings/notifications/webhook.tsx
- src/pages/settings/notifications/webpush.tsx
Logs & notification settings pages are missing route guards, resulting in errors if a user without the required `MANAGE_SETTINGS` permission attempts to directly navigate to one of those pages by entering the URL.
N/A
N/A
> fix(frontend): add missing route guards to settings pages

- server/routes/request.ts
- Do not set `modifiedBy` user for auto-approved requests submitted by a user for themselves
- Set `modifiedBy` user for all requests submitted on behalf of other users
N/A
N/A
> fix(requests): appropriately set modifiedBy user for new requests

- server/interfaces/api/settingsInterfaces.ts
- server/lib/settings.ts
- src/components/Login/LocalLogin.tsx
- src/components/ResetPassword/RequestResetLink.tsx
- src/components/ResetPassword/index.tsx
- src/components/Settings/Notifications/NotificationsEmail.tsx
- src/components/UserList/index.tsx
- src/context/SettingsContext.tsx
- src/i18n/locale/en.json
- src/pages/_app.tsx
Password reset and generation require both an application URL to be set and the email agent to be enabled.
Currently, we do not enforce this... so password reset/generation emails are sent with broken links when the application URL is not configured.
- Do not show the password reset button if requirements are not met
- Enforce and make note of the application URL requirement in the `Create Local User` modal, and only show the alert to users with the `Manage Settings` permission
- Remove weird gray line above local login / password reset fields
N/A
> fix: check that application URL and email agent are configured for password reset/generation

- src/components/Settings/SettingsPlex.tsx
Require Plex to be configured to initiate a library sync, and require libraries to be selected to perform a library scan.
N/A
> fix(plex): disable library sync if Plex not configured, and disable scan if no libraries

- package.json
- src/components/Settings/SettingsPlex.tsx
- yarn.lock
Resolves build error from #1751 
Bumps [prettier](https://github.com/prettier/prettier) from 2.3.0 to 2.3.1.
- [Release notes](https://github.com/prettier/prettier/releases)
- [Changelog](https://github.com/prettier/prettier/blob/main/CHANGELOG.md)
- [Commits](https://github.com/prettier/prettier/compare/2.3.0...2.3.1)
---
updated-dependencies:
- dependency-name: prettier
dependency-type: direct:development
update-type: version-update:semver-patch
...
Signed-off-by: dependabot[bot] <support@github.com>
> build(deps-dev): bump prettier from 2.3.0 to 2.3.1

- docs/support/need-help.md
Small typo fix: 'Overseerr' instead of 'Overseeerr'.
N/A
- Fixes none
> docs: fix small typo

- server/api/plexapi.ts
- server/lib/scanners/plex/index.ts
Plex scans on empty libraries are failing because the library contents are `undefined`.
N/A
N/A
> fix(plex): do not fail to scan empty libraries

- src/components/ResetPassword/RequestResetLink.tsx
- src/components/ResetPassword/index.tsx
- src/i18n/locale/en.json
- Remove the `a` from `Email a Recovery Link`
- Use global `save`/`saving` strings for button on password reset form (to be consistent with password page in user settings)
N/A
> fix(lang): minor changes to password reset strings

- server/entity/MediaRequest.ts
- server/subscriber/MediaSubscriber.ts
The overviews for some media items on TMDb are ridiculously long (1000+ characters), which results in notifications failing to send because the acceptable payload size is exceeded.
This PR truncates the media overviews in notifications to 500 characters or less (breaking on whitespace only, and appending `…` when truncation occurs) to avoid such notification failures.
N/A
N/A
> fix(notif): truncate media overviews

- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/UserProfile/UserSettings/UserPasswordChange/index.tsx
General Settings, Plex Settings, and User Settings Password forms do not currently disable the submit button when there are invalid inputs.
N/A
N/A
> fix(ui): do not allow submission of invalid form inputs

- docs/using-overseerr/notifications/email.md
The `Enable SSL` setting was replaced with a more clear/flexible `Encryption Method` setting in #1549.
N/A
N/A
N/A
> docs: update email agent documentation (#1797) [skip ci]

- src/components/Login/index.tsx
- src/components/ResetPassword/RequestResetLink.tsx
- src/components/ResetPassword/index.tsx
The new logo is not being centered on the password reset pages.
N/A
> fix(ui): center logo on password reset pages

- server/entity/User.ts
- src/components/RequestModal/QuotaDisplay/index.tsx
- src/components/UserProfile/index.tsx
If a user has exceeded their quota, we should display the remaining limit as 0 instead of a negative value.
- Fixes UI issue reported in #1858
> fix(ui): do not display negative remaining quota

- src/components/MovieDetails/index.tsx
- src/i18n/locale/en.json
- src/styles/globals.css
Display a max of 3 studios before prompting to expand the list
- Fixes #1489
> feat(ui): add 'show more/less...' for studios on movie details page

- server/entity/User.ts
- server/templates/email/generatedpassword/html.pug
- server/templates/email/media-request/html.pug
- server/templates/email/resetpassword/html.pug
- server/templates/email/test-email/html.pug
When the application/action URL is not configured, we should not display the `Open in ____` action link at the bottom of the email.
Also, the following refinements:
- Resize media posters to a more reasonable size
- Remove application title at the bottom of the email (it's unnecessary when you have the title at the top and action link text immediately above)
- Fix application URL for password reset emails (currently, all links in the email are to the password reset page)
- Slight refinement of language & formatting of password reset email
N/A
N/A
> fix(email): omit action link when application URL is not configured

- public/offline.html
- src/components/RequestList/index.tsx
- src/components/ResetPassword/RequestResetLink.tsx
- src/components/ResetPassword/index.tsx
- src/components/Settings/Notifications/NotificationsDiscord.tsx
- src/components/Settings/Notifications/NotificationsEmail.tsx
- src/components/Settings/Notifications/NotificationsLunaSea/index.tsx
- src/components/Settings/Notifications/NotificationsPushbullet/index.tsx
- src/components/Settings/Notifications/NotificationsPushover/index.tsx
- src/components/Settings/Notifications/NotificationsSlack/index.tsx
- src/components/Settings/Notifications/NotificationsTelegram.tsx
- src/components/Settings/Notifications/NotificationsWebPush/index.tsx
- src/components/Settings/Notifications/NotificationsWebhook/index.tsx
- src/components/Settings/SettingsLogs/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/Settings/SettingsNotifications.tsx
- src/components/Settings/SettingsPlex.tsx
- src/components/Settings/SettingsUsers/index.tsx
- src/components/UserList/index.tsx
- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsDiscord.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsEmail.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsTelegram.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsWebPush.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/index.tsx
- src/components/UserProfile/UserSettings/UserPasswordChange/index.tsx
- src/components/UserProfile/UserSettings/UserPermissions/index.tsx
- src/styles/globals.css
- Add icons to previous/next pagination buttons
- Use mail icon instead of at-symbol icon for the email notification agent
- Use ↻ symbol instead of ⤾ for the offline reload button
- Add icons to password reset page buttons
- Add icons for save & test buttons on settings pages
N/A
> refactor(ui): add/tweak icons

- overseerr-api.yml
- server/routes/request.ts
Currently, multi-season requests that would exceed a user's remaining series request quota made via the API (e.g., from Requestrr) are not being blocked if the user has at least one season request remaining.
Also add optional but missing `userId` to API docs for the `/request` POST endpoint (used for the "Request As" feature).
N/A
N/A
> fix(quota): block multi-season requests that would exceed a user's quota

- server/lib/notifications/agents/webpush.ts
"Management" type notifications (e.g., `Media Requested` and `Media Automatically Approved`) are failing to send via web push due to the user relation not being loaded in the push sub query:
```
(node:28) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'displayName' of undefined
at /app/dist/lib/notifications/agents/webpush.js:153:41
at Array.map (<anonymous>)
at WebPushAgent.send (/app/dist/lib/notifications/agents/webpush.js:150:40)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see …
```
> fix(webpush): load user in push sub query

- docs/getting-started/installation.md
This adds information to use named volumes instead of bind mounts when installing Overseerr with Docker on Windows.
N/A
N/A
- Fixes none
> docs(windows-install): update docs to use named volumes instead of bind mount

- docs/getting-started/installation.md
Sets the log level in all the example commands on the installation page in the documentation to `debug` instead of `info`. Keeping it at `info` would sometimes result in not enough information being available when users ask for support.
This shouldn't have any drawbacks since filters can be used in the log viewer to only view the log messages with a less verbose level. There will also not be an excessive amount of logs since the log files are compressed and rotated every day, capping out at a maximum of 7 days.
N/A
N/A
- Fixes none
> docs(installation): increase log level in example commands in install docs

- server/routes/issue.ts
- server/routes/issueComment.ts
- src/components/IssueDetails/IssueComment/index.tsx
- src/components/IssueDetails/IssueDescription/index.tsx
- src/components/IssueDetails/index.tsx
Non-admin users should not be permitted to delete issues that have been commented on.
Also, all users should only be permitted to edit their own comments.
Additionally, fixes bug where the user ID is being checked against the issue ID rather than the ID of the issue creator.
N/A
N/A
> fix(issues): only allow edit of own comments & do not allow non-admin delete of issues with comments

- Dockerfile
It appears that `python` was finally removed from the Alpine Linux package repositories, so we need to install `python3` instead.
N/A
N/A
> fix(docker): explicitly install python3

- src/components/Layout/SearchInput/index.tsx
Right now, hitting return when focused on the search bar does not close the keyboard. This adds a keyup handler so that hitting return blurs the search input field and thus closes the keyboard.
https://user-images.githubusercontent.com/20923978/140329958-2d84a6a0-dc74-4796-9aee-bf05fd977d20.mp4
- Fixes none
> feat(search): close search bar when hitting return

- server/api/plexapi.ts
- server/index.ts
Overseerr should not fail to start if the Plex library settings migration fails.
N/A
- Fixes #2253
> fix: handle Plex library settings migration failure gracefully

- server/index.ts
Resolves new LGTM warning: https://lgtm.com/projects/g/sct/overseerr/alerts/?mode=tree&ruleFocus=1514536246456
Documentation of `secure` cookie option (see part about `'auto'` special value): https://github.com/expressjs/session#cookiesecure
N/A
> fix: secure session cookie

- server/interfaces/api/settingsInterfaces.ts
- server/routes/settings/index.ts
- src/components/Settings/SettingsLogs/index.tsx
This mostly changes the regexp that's used to parse logs messages for the log viewer.
It's now stricter and more specific. The log file is split right at the newline followed by the timestamp instead of just the newline since unexpected log messages like errors from Typeorm span more than just one line like:
```
2021-11-21T17:47:24.460Z [error]: Could not find any entity of type "MediaRequest" matching: {
"where": {
"id": 1391
},
"relations": [
"requestedBy",
"modifiedBy"
]
}
```
The better regexp also doesn't break when encountering titles like below which would incorrectly match the regexp for the JSON structured data in the log message:
```
2021-11-21T17:57:08.979Z [debug][Plex Scan]: Updating existing title: Lord El-Melloi II's Case Files {Rail Zeppelin} Grace note
```
N/A
N/A
- Fixes …
> fix(logs): handle unexpected log messages

- server/routes/settings/radarr.ts
- server/routes/settings/sonarr.ts
When testing the connection to a Radarr/Sonarr server using a base URL, if the base URL cannot be fetched, the test fails even when the base URL input by the user is valid in an attempt to auto fill the base URL for the user.
This PR makes it so that the base URL is only fetched from Radarr/Sonarr if the user has not input one. Errors when fetching the base URL from Radarr/Sonarr are also handled.
N/A
- Fixes none
> fix(servarr): handle baseurl error when testing connection

- server/routes/request.ts
- src/components/Common/Modal/index.tsx
- src/components/RequestModal/AdvancedRequester/index.tsx
For request edits, we should be checking if the request user has _changed_, instead of if it is the acting user.  (This differs from when requests are submitted, and users can only request for themselves if they lack the Manage Users permission.  When editing requests, users can only _alter_ the request user if they have the permission.)
Also fixes a minor UI bug where an empty Advanced Options box will appear in the request modal.
- Fixes ##2331
> fix(requests): do not fail request edits if acting user lacks Manage Users permission

- server/subscriber/MediaSubscriber.ts
We currently are not filtering out declined requests for the `MEDIA_AVAILABLE` notifications.
N/A
- Fixes #2342
> fix(notif): only send MEDIA_AVAILABLE notifications for non-declined requests

- server/routes/settings/index.ts
Log messages with `]` in the error message would result in the label of the log message being incorrectly parsed as everything from the actual label to that ending square bracket. This is fixed by lazily searching for the closing bracket the label is inside of in the log message.
N/A
- Fixes none
> fix(logs): handle log parsing errors

- Dockerfile
Removes contents of `/app/.next/cache` and `/tmp` from the built Docker image.  Results in ~145 MB reduction in size of the uncompressed image.
N/A
N/A
> build(docker): reduce image size

- overseerr-api.yml
- server/lib/notifications/agents/discord.ts
- server/lib/settings.ts
- server/routes/user/usersettings.ts
- src/components/Settings/Notifications/NotificationsDiscord.tsx
- src/i18n/locale/en.json
Some admins may be sending Discord notifications to a channel that their users do not have access to.
This PR adds a setting to the Discord agent, to allow admins to enable/disable mentions (and the notification type selector in user settings).
By default, this setting is enabled, so the behavior is unchanged for users already utilizing the Discord agent.
N/A
> feat(discord): add 'Enable Mentions' setting

- overseerr-api.yml
- server/routes/request.ts
Adds additional request count data to the `/request/count` API endpoint.
N/A
> feat(api): add additional request counts

- src/components/Common/Badge/index.tsx
- src/components/IssueList/IssueItem/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/RequestCard/index.tsx
- src/components/RequestList/RequestItem/index.tsx
- src/components/StatusBadge/index.tsx
- src/components/TvDetails/index.tsx
Modifies `StatusBadge` component to deeplink to media page with management slideover panel open when `tmdbId` and `mediaType` are defined.
Otherwise, falls back to the current behavior of linking to either `plexUrl` or `serviceUrl` depending on the status.  This fallback is kept because it is useful when the TMDb ID is no longer valid (see #2181).
Also links issue status badges to issue pages.
N/A
- Closes #2353
> feat(frontend): open media management slideover on status badge click

- docs/using-overseerr/notifications/pushbullet.md
- overseerr-api.yml
- server/lib/notifications/agents/pushbullet.ts
- server/lib/settings.ts
- src/components/Settings/Notifications/NotificationsPushbullet/index.tsx
- src/i18n/locale/en.json
This adds the ability to specify a channel tag when using the Pushbullet notification agent in the server settings.
N/A
- Fixes #2087
> feat(notif): add Pushbullet channel tag

- server/routes/settings/index.ts
`Object.assign` only sets the object's property's value itself, and not its nested properties (if any), therefore log messages like the ones from the Plex Scan, where the TMDb ID, IMDB ID & TVDB ID are under the `mediaIds` property, did not have those added as extra "data" for the log message.
This replaces the usage of `Object.assign` with lodash's `set` method.
N/A
- Fixes none
> fix(logs): handle log message nested extra properties

- overseerr-api.yml
This adds the missing parameter `guid` in the openapi spec for the `/auth/reset-password/{guid}` endpoint.
N/A
- Fixes none
> docs: add missing param to reset password endpoint

- server/api/servarr/radarr.ts
- server/lib/scanners/radarr/index.ts
This uses the `hasFile` property instead of the `downloaded` property to check if a movie is available in Radarr.
I'm not sure when the `downloaded` property has been deprecated, but I can't seem to find references to it from a quick search on the Radarr repo. 
Reference: [`getMovie`](https://radarr.video/docs/api/#/Movie/getMovie).
N/A
- Fixes none
> fix(radarr): correctly check for existing movies

- server/api/servarr/sonarr.ts
Existing series are not being monitored in Sonarr (only the requested seasons are) upon request approval.
N/A
- Fixes [issue reported on Discord](https://discord.com/channels/783137440809746482/785475034725482498/943513886970236958)
> fix(sonarr): monitor existing series upon request approval

- src/utils/plex.ts
As noted by SwiftPanda each client needs a unique identifier
https://discord.com/channels/783137440809746482/793885156569514046/950083089575583824
Correctly shows up as to different clients in plex:
https://cln.sh/8WVXeHKYHsrbDqut0ycg
> fix(plex): use unique client identifier

- .gitignore
Was working on some changes today and noticed a gzipped JSON log that wasn't ignored by `git`.  I believe we are only supposed to retain a single JSON log file though, so this shouldn't affect prod envs where Overseerr is running when the log rotation happens.
N/A
N/A
N/A
> chore: gitignore gzipped JSON logs

- src/components/Layout/SearchInput/index.tsx
Disables autocomplete on main search field.
Autocomplete can clutter the UI with your past searches which are no longer relevant.
> fix(frontend): disable autocomplete on search field

- src/components/MovieDetails/index.tsx
- src/components/StatusBadge/index.tsx
- src/components/TvDetails/index.tsx
- Missing additional logic is required for badges on movie/series detail pages to open the management slideover (since we wrapped internal badge links with the `Link` component)
- Play button on series detail pages is missing request permission verification for the non-4K Plex link
- Play button on movie/series detail pages is missing verification of 4K requests being enabled for the 4K Plex link
- Request managers should be able to see 4K status badges on movie/TV detail pages even if they lack 4K request perms (they can see the badges on the request list already)
- Status badge is missing verification of user permissions for Plex link
N/A
N/A
> fix(frontend): various fixes

- server/api/themoviedb/index.ts
- server/lib/search.ts
- server/routes/search.ts
Similarly to #2082, this adds the ability to make a search for "chris year:2005" and only get results (movies & shows) that were released in the year 2005 and have "chris" in the title.
Also removed the `SearchProvider`'s IDs since they weren't of any use.
N/A
- Fixes none
> feat(search): filter search results by year

- server/api/tautulli.ts
- server/routes/user/index.ts
Currently, the user "recently watched" results are the result of deduping a single Tautulli `get_history` API call.  This PR changes the behavior to fetch additional results until there are 20 unique media, in case a user watches a lot of TV shows (especially long-running series with many episodes).
N/A
N/A
> fix(tautulli): fetch additional user history as necessary to return 20 unique media

- docs/SUMMARY.md
On Gitbook, the link to the Gotify page would point to a markdown file in the repository instead of
the page on Gitbook.
N/A
None
- Fixes none
> docs(notif): add missing link for gotify

- src/utils/plex.ts
Updates Plex headers to match what Plex Web / Tautulli does.
N/A
> fix(plex): include 'Overseerr' in X-Plex-Device-Name header

- server/routes/auth.ts
- Only upgrade user to Plex user after verifying server access (the returned list of users can include users without access to the linked server)
- Do not fail local auth if unable to fetch users from plex.tv
Unfortunately, in cases where users have already had their Plex IDs added to the DB, this will require manual modification of the DB, or deletion and recreation of the user.
- Fixes #2675
- Fixes #2676
> fix(auth): resolve local/password authentication issues

- src/hooks/useSearchInput.ts
If you used the search feature and tried to manual refresh or share the link, it would reset the
query, taking you back to the home page. This will prevent that.
- Fixes #2683
> fix: manual browser refresh would redirect to home on search page

- src/components/Discover/NetworkSlider/index.tsx
Adds Paramount+ to the network slider. (@sct any thoughts on the position of it within the slider?)
- Closes #2521
> feat(discover): add Paramount+ to network slider

- src/components/ManageSlideOver/index.tsx
The playcount being 0 was displayed above the "Advanced" heading instead of being coerced into a boolean and used to evaluate a condition.
- Fixes none
> fix(ui): don't show 0 playcount in slideover

- server/api/themoviedb/index.ts
This fix changes the movie search API call to use the `primary_release_year` query param instead of the `year` param since the later would return movies not initially released in the year specified.
Before: 
After:
- Fixes none
> fix(search): use correct param to filter movies by year

- src/components/RequestBlock/index.tsx
- src/hooks/useRequestOverride.ts
- src/i18n/locale/en.json
This adds the missing language profile overrides for TV shows and displays the names of the quality profile/language profile overrides for the request instead of their ID.
Example:
- Fixes #2757
> feat(manage slideover): show more request override details

- overseerr-api.yml
Attempting to reset a password is met with a 400 error ("request.params.guid should be number") thrown by the OpenAPI validator middleware because the spec expects a number as the `guid` but a string is used instead.
N/A
- Fixes #2864
> fix(api): use correct path param type in openapi spec

- server/entity/Media.ts
- src/components/MovieDetails/index.tsx
- src/components/TvDetails/index.tsx
Plex deep link functionality that takes you straight to the iOS/iPadOS Plex app instead of the web app. Detects the device client side and serves the mobile link server side. Android deep links that are browser based do not seem to work at the moment so that is still a WIP.
- Fixes #2548
> feat: plex deep links for iOS devices

- package.json
- server/api/externalapi.ts
- server/api/themoviedb/index.ts
- yarn.lock
Trying to reduce the number of 429s we have recently been experiencing from TMDb with a rate limit on outbound TMDb requests.
- Fixes #2853
> fix(api): add rate limiter to TMDb requests to hopefully deal with 429s

- src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
- src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsDiscord.tsx
From July 22 onwards, new Discord accounts will have 19 digit Discord IDs (https://snowsta.mp/?l=en-us&z=6&f=atx10uuark-7ps), this is similar to #971 in terms of how it changes the regex.
NA
NA
No such issue reported yet as the bug could only occur after July 22 at the earliest
> fix: update Discord ID regex to include 19 digit IDs

- server/logger.ts
Lowercases `LOG_LEVEL` value.
- Fixes #2902
> fix: log level value should not be case sensitive

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.local
- snap/snapcraft.yaml
`arm` builds are currently failing because cypress fails to install.
> build(docker): skip cypress install & bump node version

- overseerr-api.yml
- server/constants/media.ts
- server/entity/MediaRequest.ts
- server/routes/request.ts
- src/components/RequestBlock/index.tsx
- src/components/RequestButton/index.tsx
- src/components/RequestCard/index.tsx
- src/components/RequestList/RequestItem/index.tsx
- src/components/RequestList/index.tsx
Request button ordering is now as follows:
1. `View Request`
2. `Approve Request` or `Approve X Requests`
3. `Decline Request` or `Decline X Requests`
4. `View 4K Request`
5. `Approve 4K Request` or `Approve X 4K Requests`
6. `Decline 4K Request` or `Decline X 4K Requests`
7. `Request`
8. `Request More`
9. `Request 4K`
10. `Requests More in 4K`
(Note for reviewers: The `RequestButton` component was really just reordered; there were no logic changes to the conditions for displaying each option. It looks like a lot changed, but this isn't really the case 😅)
While I was working on the above, I realized that failed requests resulted in odd, undesired behavior because they currently have a `MediaStatus` of `UNKNOWN`. It is assumed that `UNKNOWN`-status media items should be requestable, but …
> fix: better ordering of RequestButton options & properly handle failed requests

- .github/workflows/snap.yaml
We already lint/test PRs, so it isn't necessary to perform this step again when building the snap images. See #2437
Also bumps `styfle/cancel-workflow-action`.
> ci: don't lint/test in snap publish workflow

- cypress/e2e/user/user-list.cy.ts
- src/components/UserList/index.tsx
- src/i18n/locale/en.json
The delete user modal will now show the user that is being deleted and the delete button will now ask you to confirm deletion similar to the delete request button.
- Fixes #2706
> feat: user delete modal shows username and requires confirmation

- cypress/e2e/login.cy.ts
- server/lib/permissions.ts
- src/components/Discover/index.tsx
- src/components/PermissionEdit/index.tsx
- src/i18n/locale/en.json
Adds a new "View Recently Added" permission as a child of the "Manage Requests" permission.
There will be no changes for users with request management permissions, but this permission will need to be granted to all other users in order for them to continue to see the "Recently Added" slider on the Discover page.
- Closes #1841
> feat(perms): add new permission for viewing recently added media

- server/entity/MediaRequest.ts
- server/lib/notifications/agents/agent.ts
- server/lib/notifications/agents/discord.ts
- server/lib/notifications/agents/email.ts
- server/lib/notifications/agents/gotify.ts
- server/lib/notifications/agents/lunasea.ts
- server/lib/notifications/agents/pushbullet.ts
- server/lib/notifications/agents/pushover.ts
- server/lib/notifications/agents/slack.ts
- server/lib/notifications/agents/telegram.ts
- server/lib/notifications/agents/webhook.ts
- server/lib/notifications/agents/webpush.ts
- server/lib/notifications/index.ts
- server/lib/watchlistsync.ts
- server/routes/settings/notifications.ts
- server/subscriber/IssueCommentSubscriber.ts
- server/subscriber/IssueSubscriber.ts
- server/subscriber/MediaSubscriber.ts
- src/components/NotificationTypeSelector/index.tsx
- src/hooks/useUser.ts
- src/i18n/locale/en.json
Adds new `MEDIA_AUTO_REQUESTED`, which notifies a user of their own auto-requested media. Only the requesting user receives this notification, as admin/system notifications of other types will already be triggered for these events.
> feat(notif): auto-request notif type

- src/components/Settings/SettingsMain.tsx
A few versions ago, NextJS fixed the local image generation to pass the cache control header from the origin. This means the locally created images are now correctly cached in the user's browser and performance has improved!
- Fixes #XXXX
> feat: restore option to cache and optimize images locally

- src/components/UserList/index.tsx
The username would show undefined in the delete modal due to the user not being stored in state. OnOk and onCancel will now store the user.
- Properly uses displayName instead of username.
> fix: prevents username showing as undefined

- next.config.js
For some reason, in NextJS 12.2, scroll restoration no longer works as it used to.
There is a new experimental flag `scrollRestoration` in the configuration we can enable though to restore the scroll restoration to the way it used to be.
- Fixes #XXXX
> fix: scroll restoration

- overseerr-api.yml
- server/routes/settings/index.ts
- src/components/Settings/SettingsLogs/index.tsx
This adds a search box on the Logs page of the Settings that filters log messages. Log messages will be filtered by their `label`, the `message` or any of the extra information that's in the `data` attribute of a log message.
Why also the extra information that's in the `data` attribute? Because I can search for "10764" and the log message
```
2022-02-03T12:01:14.564Z [debug][Plex Scan]: GUIDs are cached. Skipping metadata request. {"mediaIds":{"imdbId":"tt0830515","tmdbId":10764,"tvdbId":400},"title":"Quantum of Solace"}
```
will be matched.
I'm not sure about my use of the `useDebouncedState` hook, but I do think I missed the mark and am not using it correctly here 👀
Desktop:
Mobile:
- Fixes #2290
> feat(logs): add search filter

- src/components/PullToRefresh/index.tsx
- src/styles/globals.css
Compatibility issues with animation-spin and ring utility being used on Safari. I placed the animation on the outer div to solve this.
- Icon would render as a square on animation causing clipping on the outer edges of the ring.
- Added a slight amount of padding to outer divs.
> fix: pull to refresh compatibility issue with safari

- server/api/plexapi.ts
The "Recently added" API request will now include the `X-Plex-Container-Size` header. It will always ask for 500 items even though it's unlikely there will ever be that many. In any odd case where someone adds 500 items at once they should be performing a full scan anyways.
- Fixes #2865
> fix(plex): add container-size header to recently added api call

- src/components/RequestCard/index.tsx
- src/components/RequestList/RequestItem/index.tsx
Updates both RequestList/RequestItem and RequestCard components to no longer show `ALL` if all seasons are requested.
Originally, the number of requested seasons was added onto the `ALL` request (ie `ALL - 4`). After some discussion, it was decided to remove the `ALL` badge to keep the requests consistent. 
When viewing the request list / request cards, if `ALL` seasons are requested, it will show each of the seasons requested, compared to the `ALL` badge that would show before.
<details>
<summary>Original PR</summary>
Updates both RequestList/RequestItem and RequestCard components to contain number of seasons if 'ALL' seasons are requested
When viewing the request list / request cards, if `ALL` seasons are requested, this will include the number of seasons in the badge. If scrolling …
> fix(ui): remove 'all' badge from request cards

- server/api/themoviedb/interfaces.ts
- server/models/Tv.ts
- src/components/TvDetails/Season/index.tsx
- src/components/TvDetails/index.tsx
This fixes the air date being displayed as "January 1, 1970" in the episode list when it's not available.
Before:
After:
- Fixes none
> fix(ui): hide invalid dates in episodes list

- src/components/Common/Button/index.tsx
> fix: remove backdrop-blur class from warning buttons

- docs/extending-overseerr/reverse-proxy.md
The updated `next.js` dependency has a new regex match in the code for `/^\/_next\/data\//`.
The current `sub_filter` creates invalid regex `/^\/overseerr/_next\/data\//`.
```nginx
sub_filter '/_next' '/$app/_next';
```
It needs to be updated to substitute the correct the regex `/^\/overseerr\/_next\/data\//`.
```nginx
sub_filter '\/_next' '\/$app\/_next';
sub_filter '/_next' '/$app/_next';
```
Note: Remember to clear your browser cache (and other caches e.g. Cloudflare) after updating your Nginx config.
- Fixes #3042
> docs(proxy): update `sub_filter` for subfolder [skip ci]

- src/components/Layout/Sidebar/index.tsx
Safe area inset on top placement was being overridden by top placed on the component. This would only affect the slideover when using the PWA version.
- Added !important to prevent this issue again.
> fix: slideover close button placement when using PWA

- server/api/themoviedb/interfaces.ts
- server/job/schedule.ts
- server/models/Tv.ts
- server/routes/person.ts
- src/components/CollectionDetails/index.tsx
- src/components/Common/Tooltip/index.tsx
- src/components/Settings/SettingsMain.tsx
- src/components/StatusBadge/index.tsx
- src/components/TvDetails/Season/index.tsx
- src/i18n/locale/en.json
- Hide available media when the setting "Hide Available Media" is enabled on the `person` page
- Fixed a copy-paste error for the label for the new image cache setting
- Fixed bug that would show tooltips on the `collection` page (that badge doesn't open anything when clicked nor would the tooltip have any description)
- Replaced a weird empty space when there are no episodes in a season and the episodes list is expanded - preventing the episodes list from expanding would be unexpected for the user since there'd be nothing to indicate that it shouldn't be expandable (picture below)
- Set Plex Watchlist Sync job to short interval
Before:
After:
- Fixes #3025
> fix(ui): minor fixes

- overseerr-api.yml
The request endpoint now accepts `all` in lieu of an array of season numbers, and the API spec needs to be updated to reflect this.
Also defines request body schema for updating requests.
> fix: update API docs to allow 'all' seasons value

- package.json
Update semantic-release to use `GIT_SHA` instead of `GITHUB_SHA` as per [the build arguments documentation on semantic-release](https://github.com/esatterwhite/semantic-release-docker#build-arguments)
- [N/A] Successful build `yarn build`
- [N/A] Translation keys `yarn i18n:extract`
- [N/A] Database migration (if required)
- Fixes #2820
> Update semantic-release to use proper arg for commit tag

- src/components/PullToRefresh/index.tsx
Scrolling performance improved if window is at the top of the page. There was also an issue if a modal was active that would prevent a user from scrolling up. Mostly affected the Slideover modal. 
- distIgnore option added to ignore PTR until after a certain distance is pulled.
- Layout will check if body overflow is set to hidden or visible.
> fix: improved PTR scrolling performance

- src/components/StatusBadge/index.tsx
Tooltip would show scroll even if not necessary. Changed overflow to overflow-y-auto to show if needed.
> fix: changed overflow scroll to only if necessary

- src/components/StatusBadge/index.tsx
Tooltip wouldn't display if not in progress. Furthermore, added conditional to prevent tooltip from being interactive if only mediaLinkDescription is present.
> fix: tooltip shows properly if not in progress

- src/components/StatusBadge/index.tsx
Background opacity was missing from the progress bar. Yikes.
> fix: added bg opacity because i forgot

- .github/workflows/codeql.yml
- README.md
Update to use github's codeql workflow since LGTM won't be a thing anymore.
They auto-opened a PR for us in #3113 but wanted to make a few extra changes to the PR.
- Closes #3094
> chore: update to use github codeql

- src/components/RequestModal/TvRequestModal.tsx
- src/components/TvDetails/index.tsx
**Empty Episode Count**
Season list and request modal on the tv details page would show empty seasons. Specifically for the request modal, it would allow you to request a season with 0 episodes. Another addition in this PR is a change to the ChevronIcon for consistency across the app.
- Episode count is now added as a conditional to check for seasons.
- ChevronUpIcon changed to ChevronDownIcon
> fix: series displayed an empty season with series list/request modal

- overseerr-api.yml
'available' is not a possible request status. It already falls under the '/media/{mediaId}/available' endpoint.
Also added the meaning of each 'media' status numbers.
- Fixes #3097
> Removed 'available' from /request/{requestId}/{status} endpoint

- server/routes/request.ts
The retry logic was not updated when the criteria used to determine what a failed request is was updated in #2944. With the way failed requests are identified now, the only thing required when retrying a request is to accept it since TypeORM will update the parent media's status (for TV shows, when applicable) as well as send the request to the *arr when a request is accepted.
N/A
- Fixes #3090
> fix(request): approve request when retrying request

- src/components/Discover/CreateSlider/index.tsx
- src/components/Discover/DiscoverMovieKeyword/index.tsx
- src/components/Discover/DiscoverTvKeyword/index.tsx
- src/components/Discover/index.tsx
- src/components/Selector/index.tsx
- src/hooks/useDiscover.ts
- src/hooks/useSearchInput.ts
EncodeURIExtraParams was encoding twice with useDiscover and useSearchInput if we were on /search. Moved the function to useDiscover as encoding on the search hook is unnecessary now.
- Fixes #3237
> fix: prevent double encode if we are on /search endpoint

- src/components/TvDetails/Season/index.tsx
To provide the user more information concisely when viewing TV Details, this includes a "shorthand" for the episode `SxxExx`.  In the future, I'd like to add an on hover that shows the _absolute_ episode number. 
As it currently stands:
With the shorthand badge:
[Here's](https://discord.com/channels/783137440809746482/1027318650409062450) the discord discussion thread
While testing a few other TV Shows, sometimes it shows the absolute number. I've so far only found 1 show where this happens, so it might be limited to just it. 
When viewing One Piece, it shows the _absolute_ episode number, instead of the episode number for just that season.
Example:
While it's not the end of the world, it's not desired (I think an on hover for absolute episode number would be best).
Additionally, it's not …
> feat(ui): add episode shorthand to tv details UI (SxxExx)

- src/components/Discover/FilterSlideover/index.tsx
Prevents zooming on mobile when the date picker input is selected. Adding a slightly larger font fixes this.
> fix: screen would zoom on mobile if date picker input was selected

- server/entity/MediaRequest.ts
Failed requests whose media have become available while the request wasn't retried would fail with the error message `Media already available` when retried. This changes that behaviour to mark the request as approved instead.
N/A
- Fixes none
> fix(request): mark request as approved if media is already available when retrying failed request

- docs/getting-started/installation.md
Adds the `PORT` environment variable to the example commands when using Docker.
Also includes 2 small fixes
- a typo
- clarify hint about named volumes since the second bit of information was often skipped by users
N/A
None
- Fixes #3253
> docs(installation): add PORT env variable to example commands

- src/components/Discover/DiscoverSliderEdit/index.tsx
- src/components/Discover/index.tsx
Drag to move was a little finicky on certain devices so I added arrow icons as an alternative option. Will probably add better touch functionality soon but this should help for now.
> feat: slider chevron scroll

- src/components/Discover/DiscoverSliderEdit/index.tsx
Chevron arrow up and down icons were in the wrong place on mobile. Added specific top and right modifiers to correct placement.
> fix: arrow icons were misplaced on mobile in slider edit

- overseerr-api.yml
- server/api/themoviedb/index.ts
- server/routes/discover.ts
Adding multiple genres to the filter caused a 500 error. Query was being passed in as a number but is now passed in as a string. This is the same as we do for movie genre filtering.
- Fixes #3279
> fix: multiple genre filtering now works

- src/components/Discover/DiscoverTv/index.tsx
Series sorting was not filtering correctly when use the first date ascending or descending. Incorrect sort option was being passed in as a value. Works well now!
- Fixes #3280
> fix: series first air date filtering

- .github/workflows/ci.yml
- .github/workflows/preview.yml
- .github/workflows/release.yml
- .github/workflows/snap.yaml
The publish snap action with snapcraft 7 requires the use of an environment variable instead of a parameter to login.
Also updates the [soon-to-be deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) set-output commands in the Github Action workflows.
N/A
- Fixes #3281
> fix(build): update usage of publish snap action

- server/api/plexapi.ts
- server/lib/scanners/plex/index.ts
Plex recently added would not add any new seasons if the show was already added at least once. We will now pass in and check the Plex library based on the media type. This will make sure we will check for new seasons/episodes that are added to an existing show.
- Passed in a new prop to getRecentlyAdded for mediaType
- Type 4 will be used for shows. Type 1 used for movies.
- Fixes #3276
> fix: recently added items scan

- src/styles/globals.css
Fix styling for range sliders in Firefox.
- Fixes #3288
> fix(ui): style range thumbs correctly for firefox

- src/components/AirDateBadge/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/PersonDetails/index.tsx
- src/components/TvDetails/index.tsx
Will make sure the series air dates are using the correct UTC timezone. Previously, series air dates were one day off. Included an example of The Last of Us now showing the correct First and Next Air Date.
- Fixes #3289
> fix: air date will use UTC for timezone

- server/lib/imageproxy.ts
> fix(snapcraft): use the correct config folder for image cache

- next.config.js
This increases the threshold for the warning about the amount of data sent when doing server-side rendering from 128KB (the default) to 256KB since the strings for the locale make up almost all of that data already. This warning also gets noticed by users looking at their container logs when something isn't working as expected and may be something that they mistakenly focus on to try to diagnose their issue.
N/A
- Fixes none
> fix: increase threshold for amount of data to be fetched when SSR'ing

- src/components/ManageSlideOver/index.tsx
Full title will show on hover now in the manage slideover.
- Tooltip component added to DownloadBlock in ManageSlideover.
- Fixes #3286
> feat: full title on hover with tooltip

- server/index.ts
- server/middleware/clearcookies.ts
This is only a problem if CSRF protection is enabled.
CDNs like Cloudflare bypass their cache if cookies are set in the response.
clearCookies middleware removes the header before imageproxy serves the image.
I initially considered creating a `middlewares` collection and removing CSRF protection from the list if it is present for the image proxy, but removing the header is a much simpler solution.
_none_
> perf(server/index.ts): do not set cookies to image proxy so CDNs can cache images

- server/lib/settings.ts
This doesn't really change anything, I just noticed that there is an additional parenthesis that was added into the API key data before being encoded. 🤷🏻
- Fixes #XXXX
> chore: remove unnecessary parenthesis

- server/job/schedule.ts
- src/components/CollectionDetails/index.tsx
- src/components/MovieDetails/index.tsx
- src/components/RequestCard/index.tsx
- src/components/RequestList/RequestItem/index.tsx
- src/components/Settings/SettingsJobsCache/index.tsx
- src/components/TvDetails/index.tsx
- src/i18n/locale/en.json
- src/utils/refreshIntervalHelper.ts
Progress bar would not fetch new download status progress if page was not refocused or reloaded. To solve this, I added a refreshInterval if there is a download to watch. I also added in a change to make the download sync editable, in case you want to grab the download status at a faster rate.
- Each component we will call refreshIntervalHelper to see if downloadStatus contains items and then update the timer accordingly.
- Timer set to 5000ms if items are present but this can be altered if needed.
- Download sync schedule is now editable. Editable times are 30, 45, and 60 seconds. 
- Fixes #3270
> fix: added a refresh interval if download status is in progress

- src/components/TitleCard/index.tsx
The mini status badge doesn't show status of 4K media, hence it shouldn't be displayed when media has been requested/is processing/is available in 4K only.
- Fixes #3345
> fix(ui): hide mini status badge if non-4K media status is unknown

- server/routes/discover.ts
- server/routes/user/index.ts
The `page` param was passed as a route parameter instead of a query parameter and the total amount of watchlist items/pages was being incorrectly calculated.
- Fixes none
> fix(watchlist): correctly load more than 20 watchlist items

- .vscode/settings.json
- src/components/Common/SlideOver/index.tsx
- src/styles/globals.css
Also adds a change to the workspace settings to associate the `globals.css` file to the tailwindcss language so that VS Code doesn't show 100+ warnings when opening that file 👀 
Before: 
After:
- Fixes none
> fix(ui): hide search bar behind slideover when opened

- server/lib/availabilitySync.ts
A few log levels were mistakenly configured to log at the 'info' level instead of 'warn.' They have been updated to 'warn' as they are non-critical.
> fix: corrected log levels in availability sync

- src/components/Common/Badge/index.tsx
Extremely minor fix for the badge component. The default badge opacity was adjusted slightly to include the missing hover attribute.
> fix: corrected default badge hover opacity

- src/components/CollectionDetails/index.tsx
The collections details page was missing the extra padding for the new mobile menu.
- Added the extra-bottom-space class to the collection details page.
> fix(ui): corrected mobile menu spacing in collection details

- server/api/servarr/radarr.ts
- server/api/servarr/sonarr.ts
- server/lib/availabilitySync.ts
The main objective of this PR was to address an issue wherein the series still existed within the arr service but the media was not being monitored and the corresponding file was missing. In such cases, the affected series should be removed from Overseerr. To resolve this, I added a new route for Sonarr to ensure the correct episodeFileCount was being received (a similar route for Radarr already existed), which I then integrated into the availability sync job.
- Created new Sonarr route that will let you find an existing series by its ID.
- Migrated from searching with the respective tmdbid/tvdbid to using the external service ID.
- Logs will now tell you their media ID instead of their tmdbid/tvdbid.
- Fixes #3363
> fix: availability sync file detection

- server/api/themoviedb/interfaces.ts
- server/models/Search.ts
- server/routes/discover.ts
- server/utils/typeHelpers.ts
- src/components/Common/ListView/index.tsx
- src/components/TitleCard/index.tsx
- src/i18n/globalMessages.ts
When searching for "ce soir c'", there's a 500 error, because tmdb return a 'collection' type that is not handled.
Before:
After:
- #3378
> Fix 500 & handle search of collection

- server/routes/user/index.ts
Break-up request removal into groups of 1000 requests to be removed at a time.
[Typeorm 'chunk' option documentation]( https://typeorm.io/repository-api#additional-options)
- Issues #3322
> fix: error deleting users with over 1000 requests

- src/pages/movie/[movieId]/index.tsx
- src/pages/tv/[tvId]/index.tsx
The fallback data for our movie/tv details component would not load when using a direct route to the movie/tv details page. This was due to using getInitialProps which will only run on the client when navigating to a different route via the link component or by using the router component. To correctly always load our fallback data, I modified the movie/tv details page to use getServerSideProps which will always pull the correct data.
- Movie and tv details page will now use getServerSideProps
> fix: corrected initial fallback data load on details page

- src/hooks/useLockBodyScroll.ts
Resolved an outstanding issue with Mobile Safari(webkit) that prevented the useLockBodyScroll from working. This was especially noticeable when a modal was open and you could still scroll. Adding touch action "none" to the hook fixes this issue.
- Added touch-action: none to the useLockBodyScroll hook.
> fix: lock body scroll when using webkit

- server/routes/service.ts
This PR addresses an issue with the series fallback lookup breaking when specifically using Sonarr V4. The problem has been resolved by updating the route with the newer v3 API url.
- Changed url from using /api to /api/v3
N/A
> fix: correctly load series fallback modal with sonarr v4

- server/entity/MediaRequest.ts
Stops an issue where we were assigning the radarr/sonarr tags to another tags varable, and then mutating that variable with extra user tags (not realizing that this mutation altered the actual original settings tag array).
I don't have a test setup and made this PR through the web UI, so someone else will have to pull and validate it, but it should do the trick.
- Fixes #3480
> Make a (shallow) copy of radarr/sonarr tags into a request before adding user tags

- server/api/rottentomatoes.ts
As described in #3491, in the existing code, there was a mismatch in data types when comparing the `releaseYear` property (number) of the `contentResults` object with the `year` parameter (string). This caused the comparison to fail and led to incorrect retrieval of TV show ratings, resulting in a "404 RT ratings not found" error.
To address this issue, this pull request removes the conversion of the `year` parameter to a string and instead keeps it as a number type. This change aligns the data types correctly for the comparison and resolves the issue of retrieving TV show ratings.
Before
After
- Fixes #3491
> fix: fixes RT ratings for Tvshows

- src/components/Layout/Sidebar/index.tsx
The issues icon color was gray instead of white like the rest of the icons in the sidebar. This PR fixes that!
Before
After
- Fixes #3495
> fix: corrected issues icon color

- src/components/StatusBadge/index.tsx
Minor bug fix to handle cases where the download item does not have a season/episode number.
Current behavior:
> fix(statusbadge): handle missing season/episode number

- server/api/plextv.ts
update checkUserAccess to use getUsers
getFriends() calls `pms/friends/all` which is deprecated.
getUsers() should be used instead.
- Fixes #3550
> fix: importing friends

- server/lib/availabilitySync.ts
This pull request includes improved handling of certain edge cases where media statuses were being changed to unknown and incorrect requests being were removed. Also included is a minor fix for users with a single radarr or sonarr server.
This is a temporary fix at least until we add the new media and request statuses.
- Prevent the incorrect media being set to unknown on rare occasions.
- Enhanced request handling.
- Better checks for users with single *arr servers.
N/A
> fix: handle issue causing incorrect media to change to unknown

- server/routes/settings/index.ts
We should only perform Tautulli connection checks when the settings are defined.
This PR just adds a simple check for the hostname.
- Fixes [this issue reported on Discord](https://discord.com/channels/783137440809746482/1136421536300011600)
> fix(tautulli): only test connection if hostname is defined

- src/components/Discover/NetworkSlider/index.tsx
Added Peacock to Network Slider
> feat: add Peacock to Network Slider

- server/entity/MediaRequest.ts
- server/lib/settings.ts
- src/components/Settings/SonarrModal/index.tsx
- src/i18n/locale/en.json
Added flexibility to set default anime series type in service settings. Now you can choose 'standard' for anime if you prefer it, making it easier to use features like searching for season packs on Sonarr.
- Fixes #3626
> feat: select default seriesType for anime

- .gitattributes
- cypress/config/settings.cypress.json
- public/offline.html
- public/sw.js
@hotio and @linuxserver (and perhaps others) build and publish third-party Overseerr images from tarballs created by `git archive`.
Currently, these archives contain files that aren't necessary to build Overseerr and shouldn't be included in final, built images.  This PR specifies these files/directories to be excluded in `.gitattributes`.
N/A
N/A
N/A
> chore: specify files/directories to exclude from git archives

- server/lib/watchlistsync.ts
> fix: request watchlist items sequentially to prevent bypassing quota

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.local
- snap/snapcraft.yaml
> build: update node to 20.9

- server/routes/collection.ts
- server/routes/discover.ts
- server/routes/index.ts
- server/routes/movie.ts
- server/routes/person.ts
- server/routes/search.ts
- server/routes/tv.ts
Fixes bug where language query parameter is ignored in API requests. Currently user's locale or main settings locale value is used over language specified in query for API requests to TMDB. User's may want to query the API in other languages to grab textless posters with 'xx' language query for example. 
- None
> fix: api language query parameter ignored

- src/components/MovieDetails/index.tsx
Changed the height of the container to `h-full` to ensure that media with long titles such as `Fate/Grand Order the Movie: Divine Realm of the Round Table Collection` fits into the box. This does not affect smaller titles (see attached screenshots for examples)
**Before:**
**After:**
**Other smaller titles:**
> fix(ui): ensure title fits into the `view collection` box

- overseerr-api.yml
This is to correct what I think are a couple of small issue with the api doc:
- correct indentation of get user response
- add missing parameter in slider update (as per https://swagger.io/docs/specification/describing-parameters/)
> fix(docs): correct openapi docs minor issues

- src/hooks/useDeepLinks.ts
Seems like recently the iPad detection broke for the deep link hook. We can do a similar check to what we are currently doing and see if the user agent includes type Mac (we also check if the device is touch enabled). Not the most optimal solution but the only solution as far as I'm aware of for now.
N/A
> fix: correct deep links on iPad

- server/api/plextv.ts
- server/job/schedule.ts
- server/lib/cache.ts
- server/lib/settings.ts
- server/lib/watchlistsync.ts
Prevents fetching the entire watchlist for a Plex user, when the watchlist hasn't been updated. It will now utilize the `If-None-Match` HTTP header to check whether the watchlist has been updated. Since Plex sends back a `X-Plex-Cache` header in the response, I'd presume they have some sort of caching built in to their backend.
This will also limit most sync requests going to Plex, so it is possible to increase the frequency of the sync task. I've set it to an arbitrary value of every 3 minutes, but feel free to comment about it.
Given the increased frequency, I've also limited the watchlist request, when updated, to 20 items instead of 200. I can't imagine most people add more than 20 items in 3 minutes, anyway.
- [N/A] Database migration (if required)
- Fixes #3754
> feat(watchlist): Cache watchlist requests with matching E-Tags

- src/components/Layout/PullToRefresh/index.tsx
This PR fixes an issue where the pull-to-refresh icon was incorrectly displaying in its default state on certain phones.
To resolve this, I moved the logic for detecting the initial pull-to-refresh gesture to the layout component. This change will make sure that the icon will only render when the user is at the top of the page and actively pulling down.
> fix: prevent icon from displaying on certain phones when not pulled

- src/components/IssueModal/CreateIssueModal/index.tsx
- src/components/Layout/MobileMenu/index.tsx
- src/components/Layout/Sidebar/index.tsx
- src/components/Layout/index.tsx
This PR fixes an issue where the issue/request count would not update when a request or issue was received from another user, unless navigating directly to the requests or issues page. Now if you make an action anywhere, the count should update.
Also added a slight change to the mobile menu icon for the request count.
N/A
> fix: properly update issue and request counts in certain scenarios

- src/components/Layout/MobileMenu/index.tsx
- src/components/Layout/Sidebar/index.tsx
Minor change that centers the count badge on the sidebar and on the mobile menu when expanded.
> fix: center count badge on sidebar and mobile menu

- server/api/themoviedb/index.ts
When localizing to a language other than English, the data retrieved from TMDb is also localized to that language. As a result, the `relatedVideos` data attached to a movie in Overseerr may lack the necessary information to display the "view trailer" button on the movie/TV show details page.
Fortunately, the TMDb API supports multi-language requests, allowing you to fetch video data in multiple languages.
https://www.themoviedb.org/talk/6712613425c70b8b1d67ba57?page=1
I know that the request to TMDb includes `include_video_language=en, en` when using English. However, I think that this is a small trade-off compared to adding an additional conditional check in the code.
- Fixes https://github.com/sct/overseerr/issues/1643
> Provide trailer in a fallback language when the original TMDB request doesn't provide one in the chosen localization

- public/sw.js
- server/lib/notifications/agents/agent.ts
- server/lib/notifications/agents/webpush.ts
- src/components/Layout/MobileMenu/index.tsx
- src/pages/_app.tsx
This pull request implements the app badging API, enabling the addition of a badge to the app while using the PWA. The badge will display the number of pending requests and will only be visible to admin users.
- Utilizes the navigator object to set the app badge.
- Created a specific notification payload only for admins that will tell the service worker to update the badge.
Ignore the icon logo as it was for testing purposes.
> feat: pwa badge notifications

- src/components/Layout/MobileMenu/index.tsx
Improved styling of the request count badge that is appended to the request icon button on the mobile menu. Width and height will remain static unless requests are greater than 99.
> fix: improve count badge styling

- src/pages/_app.tsx
- src/pages/collection/[collectionId]/index.tsx
- src/pages/movie/[movieId]/index.tsx
- src/pages/tv/[tvId]/index.tsx
Server side loads the IP address to bind the socket to from environment variable `HOST`, but client side expects the API to always be on localhost. This generally works, but when you have IPv6 capable server and trying to bind to IPv4 port (e.g. HOST=127.0.0.1), this does not work as client side has hardcoded `localhost` instead of using `process.env.HOST`. As IPv6 takes priority over v4, localhost resolves to ::1 resulting in internal server error.
This fix replaces all occurrences of api calls from localhost:PORT to HOST:PORT.
- Fixes #3838
> Change localhost to process.env.HOST for client requests
