public/site.webmanifest
Uses sidebar color for the background of the splash screen
- Fixes #XXXX
=> feat: dark splash screen

CONTRIBUTING.md, README.md
Fixed 2 typos in CONTRIBUTING.md and README.md
=> docs(contributing.md, readme.md): fixed 2 small typos

overseerr-api.yml, server/middleware/auth.ts, server/routes/auth.ts, src/components/Login/index.tsx, src/components/UserEdit/index.tsx, src/utils/typeHelpers.ts
Fixed a bunch of typos in .ts files.
=> docs(in code): fixed multiple typos

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Updated the issues templates to include the new labels
- Fixes #XXXX
=> docs: Update templates with new labels [skip ci]

CONTRIBUTING.md
Improves structure and readability. Also adds a section about rebasing from upstream.
=> docs(contributing.md): improve `Getting Started` in `CONTRIBUTING.md`

src/components/TitleCard/index.tsx
Fix invalid dom-nesting issue with title card
- Fixes #476
=> fix(frontend): invalid dom-nesting title card fix

overseerr-api.yml, server/api/themoviedb.ts, server/models/Collection.ts, server/models/Movie.ts, server/routes/collection.ts, server/routes/index.ts, src/components/CollectionDetails/index.tsx, src/components/Common/Button/index.tsx, src/components/MovieDetails/index.tsx, src/components/RequestModal/MovieRequestModal.tsx, src/components/TitleCard/index.tsx, src/i18n/locale/en.json, src/pages/collection/[collectionId]/index.tsx
=> feat: add collections

CONTRIBUTING.md
Fix small typo from when the contributing guidelines were revamped.
N/A
N/A
N/A
=> fix(docs): fix typo in dev installation instructions

overseerr-api.yml, server/lib/notifications/agents/email.ts, server/lib/settings.ts, src/components/Settings/Notifications/NotificationsEmail.tsx, src/i18n/locale/en.json
Got some TLS issues with testing. I assume it's because localhost isn't using TLS? Not really sure how to test this. Anyone know?
- Closes #496
=> feat(email): add sendername to email notification

.gitbook.yaml, docs/README.md, docs/SUMMARY.md, docs/extend/reverse-proxy-examples.md, docs/extending-overseerr/reverse-proxy-examples.md, docs/getting-started/installation.md, docs/support/asking-for-support.md, docs/support/faq.md
=> Docs Update

docs/README.md, docs/support/faq.md
=> docs: update introduction

docs/extending-overseerr/reverse-proxy-examples.md
Removed duplicate text in hint at the start of the document
N/A
N/A
N/A
=> docs(reverse-proxy-examples): removed duplicate text in hint

docs/getting-started/installation.md
Who needs docker ;)
_it's only docs_
- A work-around for #302
=> Add native linux install instructions

docs/getting-started/installation.md
Add install instructions for swizzin
Blocked until https://github.com/swizzin/swizzin/pull/567 is merged
N/A
=> docs: Add swizzin install instructions (#552) [skip ci]

docs/getting-started/installation.md
Added gentoo install instructions
N/A documentation only
None
=> docs: Added installation instructions for gentoo (#556) [skip ci]

docs/getting-started/installation.md
Update docs for ubuntu. Add ubuntu arm install instructions. 
N/A
=> docs: Update Ubuntu install instructions [skip ci]

docs/SUMMARY.md, docs/using-overseerr/notifications/README.md, docs/using-overseerr/notifications/webhooks.md
=> Notification docs

overseerr-api.yml, server/entity/User.ts, server/routes/auth.ts, server/routes/user.ts, src/components/PermissionOption/index.tsx, src/components/UserEdit/index.tsx, src/components/UserList/index.tsx
The local user commit introduced a bug that made you unable to save edited users
also fixed another error that was on the user edit page
=> fix(user edit): fix user edit not being able to be saved

docs/extending-overseerr/reverse-proxy-examples.md
Adding https://gravatar.com to Content-Security-Policy
- Fixes #660
=> docs: Update LE/NGINX to remove CSP [skip ci]

snap/snapcraft.yaml
=> build(snapcraft): Fix arm build by using py2

.github/workflows/ci.yml, .github/workflows/invalid_template.yml, .github/workflows/release.yml, .github/workflows/snap.yaml, .github/workflows/support.yml
=> build(workflows): Update workflows to use ubuntu-20.04

.github/workflows/ci.yml, .github/workflows/snap.yaml
Add skip ci to discord notifications 🤞
=> build(discord): Add skip ci to discord notifications [skip ci]

server/entity/User.ts, server/lib/notifications/agents/discord.ts, server/lib/notifications/agents/email.ts, server/lib/notifications/agents/pushover.ts, server/lib/notifications/agents/slack.ts, server/lib/notifications/agents/telegram.ts, server/lib/notifications/agents/webhook.ts, server/migration/1611508672722-AddDisplayNameToUser.ts, server/routes/auth.ts, server/routes/user.ts, src/components/RequestBlock/index.tsx, src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx, src/components/RequestModal/MovieRequestModal.tsx, src/components/UserEdit/index.tsx, src/components/UserList/index.tsx, src/context/UserContext.tsx, src/hooks/useUser.ts, src/i18n/locale/en.json
Part of the follow up work for local users #646 
Closes #264
=> feat(users): add editable usernames

server/api/radarr.ts
sonarr / radarr sync introduced a bug where every requested title would register as already available, making it impossible to request new items.
- Add more specific logging
- Correctly handle preexisting titles
- Update existing radarr items that are unmonitored and not downloaded
Closes #759
=> fix(radarr): fix request bug which made it impossible to add new items

server/api/radarr.ts
=> fix(radarr): return the updated data when updating radarr request

src/components/RequestList/index.tsx, src/components/Settings/SettingsJobsCache/index.tsx
`th` elements should be nested inside a `tr` element, rather than being direct children of `thead`.
This issue was only present on the Requests page and the Jobs & Cache page.
N/A (no change to UI appearance)
- Fixes #659
=> fix(html): th elements should be nested under tr, not directly under thead

package.json, server/routes/request.ts, src/components/RequestModal/AdvancedRequester/index.tsx, src/components/RequestModal/MovieRequestModal.tsx, src/components/RequestModal/TvRequestModal.tsx, src/i18n/locale/en.json, yarn.lock
Allows requesting as other users when the user has the Manage Users & Manage Requests permission. (Both are required)
- Closes #457
=> Request as another user

src/components/RequestList/RequestItem/index.tsx, src/i18n/locale/en.json
Adds avatars to the request list, just like the ones recently added to request cards!
=> refactor(ui): Display user avatars in request list

src/components/UserList/index.tsx
Currently, the validation error message is defined but not used.
=> fix(ui): Use minimum char validation message

src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx
Fix UI issues resulting from missing data.
- Fixes #858
- Fixes #859
- Fixes #861
=> fix(ui): Handle missing movie/series data

src/components/PersonDetails/index.tsx
Apply fix from 282f28f2b9d0cc8c9105d01b43d4e1f730320b8b to person detail pages.
- Fixes #880
=> fix(ui): Fix card sizes on person detail pages

src/components/Settings/SonarrModal/index.tsx
Small typo fix
Before:
After:
None
=> fix(ui): fixed anime language profile typo

src/components/Search/index.tsx, src/hooks/useSearchInput.ts
escapes * and correctly handles when search gives error
- Fixes #890
=> fix(search): Handle search errors and escape *

docs/support/faq.md
Updated various points in the documentation.
- Updated mentions of local users
- Updated mentions of Radarr/Sonarr sync
- Consistent capitalization of the word 'Sonarr' and 'Radarr'
- Updated mentions of user roles
- Updated mentions of 4K requests
N/A
None
None
=> docs: update documentation for recently implemented features

src/components/Common/PlayButton/index.tsx, src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx
Create a PlayButton component which accepts an array of links, to make it easier to add additional links in the future (e.g., for Jellyfin or Emby).
Also fixed a bug where sometimes a "0" is still shown instead of a missing rating, and replaced remaining occurrences of the `FormattedMessage` element with `intl.formatMessage()` in both `MovieDetails` and `TvDetails`.
=> refactor(ui): Create PlayButton component

server/api/plextv.ts, server/routes/auth.ts, server/routes/user/index.ts
Check for Plex server access on user import, so that only users with access are imported.
- Fixes #475
=> fix(plex): Check Plex server access on user import

.github/CODEOWNERS, docs/support/faq.md
Add information about the new Sonarr language profile required setting to the FAQ.
=> docs: Add language profile requirement info to FAQ

docs/getting-started/installation.md
Documentation only update
N/A
N/A
- Fixes frequent questions about Overseerr Swizzin installer
=> Explain Swizzin installer is not live yet and why

src/components/Settings/Notifications/NotificationsPushover/index.tsx, src/i18n/locale/en.json
Simple fix for a typo
None
None
- Fixes none
=> fix(notif): fixed typo in pushover hint

src/components/TvDetails/index.tsx, src/i18n/locale/en.json
Did not account for cases where there is only one season in my previous PR, sorry!
N/A
=> fix(lang): fix singular form of season count

src/components/RequestList/RequestItem/index.tsx
When we added plex url to the statusbadge we forgot to add this to the request item.
=> feat(requests): add plex url to request item

src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx
Status, requested by, and modified were not aligned in the request item on mobile. Plus I removed status in the request card on mobile.
=> fix(frontend): status, requested by, and modified alignment fix

server/lib/notifications/agents/telegram.ts
Adds poster image to Telegram media notifications.
N/A
=> feat(notif): include poster image in Telegram notifications

CONTRIBUTING.md, README.md
Contribution guide edits & formatting.
N/A
N/A
N/A
=> docs: edit contribution guide

package.json, src/components/LoadingBar/index.tsx, src/pages/_app.tsx, tailwind.config.js, yarn.lock
Adds a loading indicator for navigation
=> feat(frontend): add loading bar indicator

docs/support/faq.md
Added entry about base url for Sonarr entry.
- Fixes #XXXX
=> docs: add base URL info to FAQ

src/components/Slider/index.tsx, src/styles/globals.css, tailwind.config.js
Makes it clearer that disabled elements are disabled and cannot be interacted with. 😺
N/A
=> fix(ui): use appropriate cursor type for disabled input elements

next.config.js, server/interfaces/api/settingsInterfaces.ts, server/lib/settings.ts, src/components/CollectionDetails/index.tsx, src/components/Common/CachedImage/index.tsx, src/components/Common/ImageFader/index.tsx, src/components/Discover/MovieGenreList/index.tsx, src/components/Discover/MovieGenreSlider/index.tsx, src/components/Discover/TvGenreList/index.tsx, src/components/Discover/TvGenreSlider/index.tsx, src/components/GenreCard/index.tsx, src/components/Login/index.tsx, src/components/MovieDetails/index.tsx, src/components/PersonCard/index.tsx, src/components/PersonDetails/index.tsx, src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx, src/components/Settings/SettingsMain.tsx, src/components/TitleCard/index.tsx, src/components/TvDetails/index.tsx, src/components/UserProfile/ProfileHeader/index.tsx, src/components/UserProfile/index.tsx, src/context/SettingsContext.tsx, src/i18n/locale/en.json, src/pages/_app.tsx, src/styles/globals.css
Add optional caching/optimizing of TMDb images locally.
=> feat: add option to cache images locally

src/i18n/locale/en.json
=> fix(lang): remove 'requires and'

docs/SUMMARY.md, docs/using-overseerr/settings/README.md
Initial documentation of application settings.  (Plex & Services settings not yet written.)
N/A
N/A
N/A
=> docs: initial documentation of application settings

src/components/Common/ButtonWithDropdown/index.tsx, src/styles/globals.css
Set appropriate z-indices / stack order for buttons with dropdowns.
- Fixes #1229
=> fix(ui): button w/ dropdown z-indices

docs/using-overseerr/settings/README.md
Adds descriptions of Plex/Radarr/Sonarr settings to docs.
N/A
N/A
N/A
=> docs: add Plex/Radarr/Sonarr settings documentation

docs/using-overseerr/settings/README.md
Clarify that 4K servers also need to be marked as default.
N/A
N/A
=> docs: add clarification about 4K Sonarr/Radarr servers

.vscode/settings.json
This will organize the imports (including removing unused imports) when changes have been made to a file and that file is saved.
None
- Fixes none
=> style: use vscode's `organize imports`

src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
=> fix(ui): fix label formatting in general user settings

docs/using-overseerr/settings/README.md
=> docs: change wording services separate copies non-4k 4k

docs/support/asking-for-support.md, docs/support/faq.md
Organizes FAQs into appropriate categories, as well as some minor edits.
N/A
N/A
=> docs: organize and edit FAQ

docs/extending-overseerr/reverse-proxy-examples.md
Not everything in the sample Nginx subfolder conf is strictly necessary, and I think that we should remove all but what is necessary.
Of note is HSTS, which should definitely not be enabled unless the user understands the implications of doing so.
The CSP line is also something we shouldn't have to maintain.
N/A
N/A
N/A
=> docs: only include necessary lines in example Nginx subfolder conf

docs/SUMMARY.md, docs/support/faq.md, docs/using-overseerr/notifications/README.md, docs/using-overseerr/settings/README.md, docs/using-overseerr/users/README.md
Adds initial documentation for user management functionality.
N/A
N/A
=> docs: preliminary user management documentation

src/components/Settings/SettingsPlex.tsx
Plex settings page needs to be updated to reflect the change in #1379.
N/A
=> fix(frontend): autofill with Plex server address

.github/workflows/snap.yaml, snap/snapcraft.yaml
Bumps `nodejs` to `14.16.1`, and `yarn` to `1.22.10`.
N/A
N/A
N/A
=> build(snap): bump node to 14.16.1

docs/getting-started/installation.md
=> docs: update develop message (#1435) [skip ci]

server/api/servarr/radarr.ts, server/api/servarr/sonarr.ts
Currently, when we update a series in Sonarr that already exists, we trigger the search command for that series.  However, we do not do this when we update existing movies in Radarr.
This PR adds the execution of the search command for Radarr, as well as adding `try`/`catch` blocks around both searches and tidying up some of the Radarr/Sonarr logging.
- Closes #1286
=> fix(radarr): search in addition to monitoring existing movies

src/components/Layout/SearchInput/index.tsx, src/components/RequestBlock/index.tsx, src/components/Settings/CopyButton.tsx, src/components/Settings/SettingsMain.tsx, src/components/Settings/SettingsPlex.tsx, src/components/Settings/SettingsServices.tsx, src/components/Toast/index.tsx, src/styles/globals.css, tailwind.config.js
Fixes inadvertent changes from 3e5e9c0ad181926b48f73e33edd1abb0f2885fc5.
Also removes now-unnecessary Tailwind variant config. 🥳
N/A
=> fix(css): don't target button globally

src/components/RegionSelector/index.tsx, src/components/RequestModal/AdvancedRequester/index.tsx
Missed these `button` elements in #1510.
- Fixes #1513
=> fix(ui): explicitly specify width/height of Listbox dropdown icon

src/components/RegionSelector/index.tsx
Add `z-40` back to `RegionSelector`
N/A
=> fix(ui): correct RegionSelector z-index

server/entity/UserSettings.ts, server/migration/1619239659754-AddUserSettingsLocale.ts, server/migration/1619339817343-AddUserSettingsNotificationTypes.ts, server/routes/user/usersettings.ts, src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx
The default setting for `Display Language` in user settings should be the server default value.
N/A
N/A
=> fix(locale): default user locale should be the server setting

src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx, src/i18n/locale/en.json, src/styles/globals.css
- Adds buttons that allow for editing, canceling, deleting, and retrying requests directly from request cards
- The `Edit` button unfortunately is not shown for pending requests for admins, since the button doesn't fit on desktop
- Add year to request list items and request cards, styled similarly to the title cards
- This is unfortunately not visible on mobile, since it wouldn't fit
- Only show the `requestedBy` user to users with the `Manage Requests` or `View Requests` permissions (since they can only see their own requests)
- Fixes issue where long usernames were not being truncated in the request list
- **Admin view:**
- Request slider on desktop:
- Request slider on mobile:
- Request list on desktop:
- Request list on mobile:
- **User view:**
- Request slider on desktop:
- Request …
=> feat(ui): request list item & request card improvements

server/routes/auth.ts, server/routes/user/index.ts
Case should not matter for user email addresses.
Also, convert users to Plex users during Plex sign-in, if a local user with the Plex email already exists.  (Currently, only importing Plex users is doing this.)
N/A
N/A
=> fix: perform case-insensitive match for local user email addresses

src/pages/_document.tsx, tailwind.config.js
https://nextjs.org/docs/basic-features/font-optimization
Should be merged after `next` has been bumped to 10.2.2+ (`yarn i18n:extract` confirmed to be working!).
N/A
- Closes #1415
=> refactor(font): utilize Next.js built-in web font optimization

server/entity/User.ts
Attempt to fix `"Cannot read property 'toLowerCase' of null"` error. 🤔
N/A
N/A
=> fix: handle null values in User email transform

docs/using-overseerr/settings/README.md
Update documentation settings plex. Button to sync libraries with plex
- Fixes #XXXX
=> docs: update settings plex

package.json, src/components/Slider/index.tsx, yarn.lock
Resolves breaking changes for #1765
=> build(deps): bump react-spring from 8.0.27 to 9.2.3

overseerr-api.yml
Fixes some inconsistencies in the API documentation.
N/A
N/A
=> docs(api): update and correct API documentation

package.json, server/lib/email/openpgpEncrypt.ts, yarn.lock
Resolves breaking changes which caused #1715 to fail to build.
N/A
N/A
=> build(deps): bump openpgp from 5.0.0-2 to 5.0.0-3

src/components/ResetPassword/RequestResetLink.tsx
PNG extension didn't get changed to SVG 😉 
N/A
N/A
=> fix: correct logo filename

package.json, src/components/Layout/SearchInput/index.tsx, src/components/Layout/Sidebar/index.tsx, src/components/Layout/VersionStatus/index.tsx, src/styles/globals.css, yarn.lock
=> Menu Redesign

src/components/Layout/Sidebar/index.tsx, src/components/Layout/index.tsx, src/components/UserProfile/index.tsx, src/styles/globals.css
Adds back hover styling of sidebar menu items, and applies consistent font weight & styling to user profile quota display.
Also fixes a bug where the movie quota days is displayed conditionally based on the TV quota instead of the movie quota.
N/A
=> refactor(ui): tweak styling of sidebar & user profile quota display

src/components/Layout/SearchInput/index.tsx, src/components/Layout/Sidebar/index.tsx, src/components/Layout/index.tsx
=> fix (ui): change sidebar breakpoint to lg

src/components/Common/Button/index.tsx, src/components/Common/SettingsTabs/index.tsx, src/components/Common/Table/index.tsx, src/components/Settings/SettingsLogs/index.tsx
=> fix(ui): fix notifications settings buttons overflowing

src/context/LanguageContext.tsx, src/pages/_app.tsx
Adds support for Simplified Chinese display language.
N/A
N/A
=> feat(lang): add Simplified Chinese display language

package.json, server/api/plexapi.ts, server/index.ts, server/lib/cache.ts, server/lib/scanners/baseScanner.ts, server/lib/scanners/plex/index.ts, server/lib/settings.ts, server/routes/settings/index.ts, server/types/plex-api.d.ts, tsconfig.json, yarn.lock
=> feat(plex-scan): plex scanner improvements

src/components/Setup/index.tsx
Fixes backdrops on setup page (broken in #2206).
N/A
=> fix(frontend): setup page backdrops

src/context/LanguageContext.tsx, src/pages/_app.tsx
Adds Polish display language option. :)
N/A
=> feat(lang): add Polish display language

src/components/Common/Badge/index.tsx
Badges in request list are having underline and text color applied on hover, when they should not.
N/A
=> fix(ui): request badge styling in request list

server/entity/MediaRequest.ts, server/lib/notifications/agents/email.ts, server/lib/notifications/agents/webpush.ts, server/subscriber/MediaSubscriber.ts
Adds support for 4K media notifications.
N/A
N/A
=> feat(notif): 4K media notifications

src/components/IssueDetails/index.tsx, src/i18n/locale/en.json
Adds missing translation string for placeholder string for issue comment box.
N/A
N/A
=> fix(lang): add missing string

server/routes/settings/index.ts
Verifies that the Plex user has an email address.
N/A
N/A
=> fix(plex): user import

server/lib/scanners/sonarr/index.ts
TVDB season numbers do not necessarily match those in TMDb, in which case the Sonarr scan should not process the media.
N/A
NA
=> fix(sonarr): only scan seasons that exist in TMDb

server/lib/email/openpgpEncrypt.ts
Adds handling/logging of promise rejection in PGP encryption.
N/A
- Fixes #2510
=> fix(email): enclose PGP encryption logic in try/catch

src/context/LanguageContext.tsx, src/pages/_app.tsx
Adds Albanian display language.
N/A
N/A
=> feat(lang): add Albanian display language

src/components/IssueModal/CreateIssueModal/index.tsx, src/components/NotificationTypeSelector/index.tsx, src/components/ResetPassword/RequestResetLink.tsx, src/components/ResetPassword/index.tsx, src/components/Settings/Notifications/NotificationsDiscord.tsx, src/components/Settings/Notifications/NotificationsEmail.tsx, src/components/Settings/Notifications/NotificationsGotify/index.tsx, src/components/Settings/Notifications/NotificationsLunaSea/index.tsx, src/components/Settings/Notifications/NotificationsPushbullet/index.tsx, src/components/Settings/Notifications/NotificationsPushover/index.tsx, src/components/Settings/Notifications/NotificationsSlack/index.tsx, src/components/Settings/Notifications/NotificationsTelegram.tsx, src/components/Settings/Notifications/NotificationsWebPush/index.tsx, src/components/Settings/Notifications/NotificationsWebhook/index.tsx, src/components/Settings/RadarrModal/index.tsx, src/components/Settings/SettingsJobsCache/index.tsx, src/components/Settings/SettingsMain.tsx, src/components/Settings/SettingsPlex.tsx, src/components/Settings/SettingsUsers/index.tsx, src/components/Settings/SonarrModal/index.tsx, src/components/UserList/index.tsx, src/components/UserProfile/UserSettings/UserGeneralSettings/index.tsx, src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsDiscord.tsx, src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsEmail.tsx, src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsPushbullet.tsx, src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsPushover.tsx, src/components/UserProfile/UserSettings/UserNotificationSettings/UserNotificationsTelegram.tsx, src/components/UserProfile/UserSettings/UserPasswordChange/index.tsx, src/styles/globals.css
CSS issue reported by @danshilm from latest Tailwind CSS version bump.
N/A
=> fix(css): rename form-input to form-input-area

.github/workflows/ci.yml, .github/workflows/release.yml
No need to lint/test on pushes prior to building the Docker/snap images, as the PR changes are already being linted/tested :)
N/A
N/A
N/A
=> ci: only lint/test PRs

overseerr-api.yml, server/routes/issue.ts
This adds an `/issue/count` endpoint like the `/request/count` endpoint.
N/A
- Fixes #2709
=> feat(api): add issue counts endpoint

.dockerignore, .github/workflows/cypress.yml, .gitignore, cypress.config.ts, cypress/config/settings.cypress.json, cypress/e2e/discover.cy.ts, cypress/e2e/login.cy.ts, cypress/e2e/movie-details.cy.ts, cypress/e2e/tv-details.cy.ts, cypress/e2e/user/user-list.cy.ts, cypress/support/commands.ts, cypress/support/e2e.ts, cypress/support/index.ts, cypress/tsconfig.json, package.json, server/scripts/prepareTestDb.ts, src/components/Common/Header/index.tsx, src/components/Common/Modal/index.tsx, src/components/Layout/Sidebar/index.tsx, src/components/Layout/index.tsx, src/components/Login/LocalLogin.tsx, src/components/MovieDetails/index.tsx, src/components/Slider/index.tsx, src/components/TitleCard/index.tsx, src/components/TvDetails/index.tsx, src/components/UserList/index.tsx, yarn.lock
=> test: add cypress foundation

cypress.config.ts, cypress/e2e/user/user-list.cy.ts
=> test: add waits in user test

server/routes/service.ts
Hello, since my issue got staled and the linked PR as well, I decided to implement the suggested code review in #2809. Hope that is okay.
- Fixes #2801
=> fix(api): lookup shows using english title only

src/context/LanguageContext.tsx, src/pages/_app.tsx
Hebrew, Hindi, and Romanian are also new languages on Weblate, but currently only have a few (or no) strings translated.
=> feat(lang): add Arabic and Lithuanian display languages

.gitignore, .vscode/extensions.json
Also adds `.eslintcache` to `.gitignore`
N/A
N/A
=> chore(vscode): remove deprecated npm extension from recommendations

.github/workflows/ci.yml, Dockerfile, Dockerfile.local, snap/snapcraft.yaml
=> build(docker): downgrade to node 16.16

renovate.json
Also adds prettier `groupName` for GH Action deps PRs.
=> chore(deps): update renovate config to group node container deps

.github/workflows/release.yml, .github/workflows/snap.yaml, snap/snapcraft.yaml
=> build(snap): re-enable snap workflow

src/components/TvDetails/index.tsx, src/i18n/locale/en.json
=> fix(lang): manage movie -> manage series

src/components/Login/index.tsx, src/components/Setup/index.tsx
=> fix: use image.tmdb.org for setup/login backdrop images

src/pages/_app.tsx
=> fix: use fallbackData to prepare user data during SSR

src/components/Common/SlideOver/index.tsx, src/components/ManageSlideOver/index.tsx
=> refactor: slideover redesign

src/components/ManageSlideOver/index.tsx
- Even if we don't have watch data, we can display the Tautulli button if we have a Tautulli URL
- Check for watch data, not play count (display 0 play counts)
- Remove "double border" between Tautulli watch data & button (since colors changed)
=> fix: watch data not required to show Tautulli button

src/components/Common/ButtonWithDropdown/index.tsx, src/components/Common/SlideOver/index.tsx, src/styles/globals.css
=> fix: correct safe margin for slideover

src/components/UserProfile/index.tsx
Missing permissions check for watchlist on user profile page.
=> fix: check perms to view watchlist slider on user profile

src/components/AirDateBadge/index.tsx, src/components/ManageSlideOver/index.tsx, src/components/TvDetails/index.tsx, src/i18n/locale/en.json
=> fix: correct spacing on season header badges

src/components/Common/Modal/index.tsx, src/components/RequestModal/TvRequestModal.tsx
=> fix: clicking outside modal closes modal again

src/components/Settings/SettingsLogs/index.tsx
Same as the delete modal PR. SettingsLogs component will now store the log state.
=> fix: settings log modal when closing

src/components/RequestModal/AdvancedRequester/index.tsx
Users without the required request permissions are not being filtered out of the "Request As" user list in the request modal. Requests submitted on behalf of these users will fail server-side, so we shouldn't allow these users to be selected.
=> fix(frontend): only allow 'request as' users w/ request perms

src/components/RequestButton/index.tsx, src/components/TvDetails/index.tsx
Partially available seasons are not requestable.
=> fix: do not display 'Request More' button if no requestable seasons

src/components/IssueDetails/index.tsx, src/components/MovieDetails/index.tsx, src/components/RequestCard/index.tsx, src/components/RequestList/RequestItem/index.tsx, src/components/TvDetails/index.tsx, src/hooks/useDeepLinks.ts
Deep links were missing on status badges and on the issue details page. Created a hook for easy reusability across components.
- Hook will take urls and return the correct one depending on device.
=> fix: added deep links to issues and status badges

src/context/LanguageContext.tsx, src/pages/_app.tsx
Croatian translation is almost complete in #3030 :)
=> feat(lang): add Croatian display language

server/api/externalapi.ts, server/api/rottentomatoes.ts
=> fix(experimental): use new RT API (sorta)

src/components/TitleCard/index.tsx
=> refactor: update mini status icons on titlecard to match badge colors

src/components/Settings/SettingsMain/DiscoverCustomization/CreateSlider/index.tsx, src/i18n/locale/en.json
=> fix: convert genre/studio to string in create slider

server/api/themoviedb/index.ts, server/api/themoviedb/interfaces.ts, server/models/Movie.ts, src/components/Common/Tag/index.tsx, src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx
=> feat: add keywords to movie/series detail pages

src/components/Common/StatusBadgeMini/index.tsx, src/components/TitleCard/index.tsx
=> refactor: update titlecard to use StatusBadgeMini

server/routes/person.ts
=> fix: restore status badges on titles on actors page when hide available media enabled

src/components/Common/StatusBadgeMini/index.tsx, src/components/TitleCard/index.tsx
=> fix: update StatusBadgeMini to shrink on title cards (and remove ring)

src/components/Discover/DiscoverSliderEdit/index.tsx, src/components/Discover/index.tsx, src/components/MediaSlider/index.tsx
=> fix: improve small screen layout for discover editing

src/components/Discover/index.tsx
=> refactor: redesign discover customization buttons

src/components/Discover/DiscoverSliderEdit/index.tsx, src/components/Discover/index.tsx, src/styles/globals.css
=> fix: correct spacing between sliders

src/components/Discover/DiscoverSliderEdit/index.tsx
=> fix: correct checkbox position (again) for slider edits

tailwind.config.js
=> fix: include new package calendar css in build

src/components/Selector/index.tsx
=> fix: correct grid sizing for webkit on streaming services

src/components/RegionSelector/index.tsx, src/components/Selector/index.tsx
=> fix: correctly restore selected streaming service filters

.github/holopin.yml
=> chore: add holopin config

src/components/Discover/index.tsx, src/components/Layout/MobileMenu/index.tsx, src/components/Layout/Sidebar/index.tsx, src/components/Layout/index.tsx, src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx, src/i18n/locale/en.json, src/styles/globals.css
=> feat: mobile menu

server/routes/issue.ts, server/subscriber/IssueCommentSubscriber.ts, server/subscriber/IssueSubscriber.ts, src/components/IssueDetails/index.tsx
- Allow users without `Manage Issues` permission to close/reopen their own issues
- Fix issue with users without `Manage Issues` permission not being notified of comments on their issues
- Fixes #3264
- Fixes #3266
=> fix: issues with issues

src/components/IssueDetails/index.tsx
=> fix: correct issue detail bottom padding on mobile displays

src/components/IssueDetails/index.tsx, src/components/MovieDetails/index.tsx, src/components/TvDetails/index.tsx, src/styles/globals.css
=> fix: create shared class to add bottom spacing

src/components/Layout/MobileMenu/index.tsx
=> fix: correctly check mobile menu permissions

src/components/Layout/MobileMenu/index.tsx
=> fix(ui): show 5 icons when possible on mobile menu

src/styles/globals.css
=> fix(ui): correct range slider styling in chrome

cypress/e2e/settings/discover-customization.cy.ts
=> test: change custom keyword for slider creation

overseerr-api.yml
There were a couple of API endpoints that I noticed had the wrong summary for them.
- Fixes #XXXX
=> chore: update descriptions for API endpoints

src/components/Selector/index.tsx
Fixes searching by genre name in Filters
- Fixes #3467
=> fix(genreselector): fix searching in Genre filter

server/job/schedule.ts
=> fix: adjust the plex watchlist sync schedule to have fuzziness

server/lib/availabilitySync.ts
This pull request addresses a rare edge case that happens when checking Plex media during the availability sync, which can lead to an error and break the loop. This can usually occur when you have an unstable Plex connection or there is an issue with the media itself.
- Added a try-catch block to the seasonExists function. The catch will now log instead of throwing the error. This ensures that any potential errors that may occur during the execution of this function are caught and prevents the loop from ending.
- Implemented an additional try-catch block in the sonarr season checker function. This should be an even rarer edge case but better to add this in as well.
N/A
- Fixes #3494
=> fix: improved handling of edge case that could cause availability sync to fail

src/components/Selector/index.tsx, src/components/Slider/index.tsx
The show more and carousel buttons within create slider were incorrectly causing form submission. Made sure to prevent the default submit within these components.
- Added type "button".
N/A
=> fix: resolved issue with create slider causing incorrect form submission

.github/workflows/ci.yml
=> ci: remove docker caching to save space after build

src/components/ManageSlideOver/index.tsx
adds some username tooltips 🤷 
- Fixes #XXXX
=> feat: add tooltips to tautulli avatars

src/context/LanguageContext.tsx, src/pages/_app.tsx
=> feat: add ko language

Dockerfile
=> build: do not link python for arm

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/snap.yaml
=> build: update docker ubuntu images to 22.04

.github/workflows/ci.yml, .github/workflows/preview.yml, Dockerfile, Dockerfile.local, snap/snapcraft.yaml
=> build: use node 18

Dockerfile
=> build: add global node-gyp for arm

snap/snapcraft.yaml
=> build: correct node version in snapcraft

src/components/Discover/StudioSlider/index.tsx
=> feat(studios): add a24 to studios list

server/api/plextv.ts, server/job/schedule.ts, server/lib/refreshToken.ts, server/lib/settings.ts, src/components/Settings/SettingsJobsCache/index.tsx, src/i18n/locale/en.json
Add API ping to refresh Plex authentification token
- [N/A] Database migration (if required)
- Fixes #3861
=> feat(plex): refresh token schedule

.github/workflows/deploy_docs.yml
=> build: fix deploy docs action
